// FIGUREN-Grids (SPRITES). GP7-CH-1 P0.a (Spec E10, Landkarte V2): mechanisch
// aus art/sprites.js herausgeloest, Inhalt und Schluessel-Reihenfolge byte-gleich.
// art/sprites.js bleibt als Fassade bestehen und re-exportiert SPRITES unveraendert,
// jeder bestehende Import bleibt gueltig.
// REINES DATEN-MODUL: keine Ausfuehrungslogik, keine Zufalls- oder Zeitquellen,
// keine Audio-/Loop-Aufrufe (Quelltext-Waechter smoke_test.mjs:1780-1791 und
// :5257-5273 sind damit erfuellt).
//
// Pixel-Grids: jedes Zeichen = PALETTE-Key, '.' = transparent.
// Maße: player_* 16x24 (SoM-Proportion, Kopf ~1/3), ghoul_* 16x20,
// übrige Figuren 16x16, HUD-Herzen 8x8, potion 10x10, fog_blob 32x16.
// Slice 2: hound_* 16x12 (Seitenansicht, Blick nach rechts), rust_* 16x18,
// Boden-Drops und boomerang_* 10x10, sparkle_*/block_spark 8x8,
// icon_weapon/armor/ring 12x12, icon_boomerang 16x16, Schild-Overlays klein.
// Laufzyklus des Helden: 4 Frames pro Richtung, Beinstellungen
// _0 = Kontakt (linkes Bein vor), _1 = Passing, _2 = Kontakt gespiegelt, _3 = Passing.
// Kontakt-Frames haben Fußsohle auf Zeile 23, Passing-Frames enden auf Zeile 22
// (Körper-Bob über den Zeichen-Anker). Sekundärbewegung: der Umhangsaum liegt
// in den Passing-Frames (_1/_3) anders als in den Kontakt-Frames (_0/_2).
//
// HELD-TONLEITER (GP7-CH-1 Phase 1a, Licht von oben LINKS):
//   _  Rimlicht warm, IMMER 1 px, nur obere Lichtkante (Kapuzenkuppel,
//      Schulterecke). ART_DIRECTION Regel 10 erlaubt warm ODER kalt nach
//      Lichtsituation der Figur — das Dorf ist fackelbeleuchtet, also warm.
//   Z  Stoff-Spitzlicht / weiche Lichtkante der linken (Licht-)Silhouette
//   ^  Stoff-Zwischenstufe (schließt die X->Z-Schlucht, Schrittverhältnis 1,50)
//   X  beleuchteter Stoff   U  Stoffmasse (Leitton)   u  Stoffschatten und
//   zugleich Umriss der LICHTSEITE (Stilregel 2: dunkelster Materialton statt k)
//   k  Umriss der SCHATTENSEITE (rechts/unten)   n  Tiefschatten
//      (Kapuzeninnenraum über dem Gesicht, Gürtellinie)
// Gesichtsfeld 5x5 in der Kapuze: n-Brauenschatten, 2 einzelne k-Augentexel,
// h-Wangenlicht links, 2-Schatten rechts. Kapuzenspitze außermittig LINKS,
// Schwertgriff bricht die Silhouette rechts oben, Saum schwingt rechts aus.

export const SPRITES = {
  // Held: Kapuzen-Wanderer, Schwertgriff über der rechten Schulter (Rückentrage)
  player_down_0: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX22222ukjYk.',
    '...uXhkhk2ukYyYk',
    '...uXhh222ukik..',
    '...uuu222uuuk...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnjjnnUuk..',
    '.ZhUuUUUUUUhuk..',
    '.uuUUXXUUUUhuuk.',
    '.uuUXXUUUUUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '..uUUUk..uUUUkk.',
    '..uUUUk..uUUUk..',
    '..uUUUk..qjqqk..',
    '..qjqqk..qjqqk..',
    '..qjqqk..qjjjk..',
    '..qjjjk..kkkkk..',
    '..kkkkk..nnnn...',
  ],
  player_down_1: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX22222ukjYk.',
    '...uXhkhk2ukYyYk',
    '...uXhh222ukik..',
    '...uuu222uuuk...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnjjnnUuk..',
    '.ZhUuUUUUUUhuk..',
    '.uuUUXXUUUUhuuk.',
    '..uUXXUUUUUUZZuk',
    '..knuuUUUUUuUZuk',
    '...uUUUk.uUUUk.k',
    '...uUUUk.uUUUk..',
    '...qjqqk.qjqqk..',
    '...qjqqk.qjqqk..',
    '...qjjjk.qjjjk..',
    '...kkkkk.kkkkk..',
    '....nnnnnnnnn...',
  ],
  player_down_2: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX22222ukjYk.',
    '...uXhkhk2ukYyYk',
    '...uXhh222ukik..',
    '...uuu222uuuk...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnjjnnUuk..',
    '.ZhUuUUUUUUhuk..',
    '.uuUUXXUUUUhuuk.',
    '.uuUXXUUUUUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '...uUUUk..uUUUk.',
    '...qjqqk..uUUUk.',
    '...qjqqk..uUUUk.',
    '...qjqqk..qjqqk.',
    '...qjjjk..qjqqk.',
    '...kkkkk..qjjjk.',
    '....nnnn..kkkkk.',
  ],
  player_down_3: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX22222ukjYk.',
    '...uXhkhk2ukYyYk',
    '...uXhh222ukik..',
    '...uuu222uuuk...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnjjnnUuk..',
    '.ZhUuUUUUUUhuk..',
    '.uuUUXXUUUUhUUuk',
    '..uUXXUUUUUUUZuk',
    '..knuuUUUUUuUZZk',
    '...uUUUk.uUUUk.k',
    '...uUUUk.uUUUk..',
    '...uUUUk.uUUUk..',
    '...qjqqk.qjqqk..',
    '...qjqqk.qjqqk..',
    '...qjjjk.qjjjk..',
    '....kkkkkkkkk...',
  ],
  // Rückansicht: Schwert komplett auf dem Rücken sichtbar
  player_up_0: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXUUuUUuk.yk.',
    '...uXUUuUUukjYk.',
    '...uXUUuUUukYyYk',
    '...uXUUuUUukiC..',
    '...uuuUuUUUkiC..',
    '.ZZ^^^nuUUUiCk..',
    '.Z^UuUnuUUUiCk..',
    '.Z^UuUXXXUiCUuk.',
    '.ZhUunnjjniCUuk.',
    '.ZhUuUUUUiCUhuk.',
    '.uuUUXXUUiCUUuk.',
    '.uuUXXUUUCUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '..uUUUk..uUUUkk.',
    '..uUUUk..uUUUk..',
    '..uUUUk..qjqqk..',
    '..qjqqk..qjqqk..',
    '..qjqqk..qjjjk..',
    '..qjjjk..kkkkk..',
    '..kkkkk..nnnn...',
  ],
  player_up_1: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXUUuUUuk.yk.',
    '...uXUUuUUukjYk.',
    '...uXUUuUUukYyYk',
    '...uXUUuUUukiC..',
    '...uuuUuUUUkiC..',
    '.ZZ^^^nuUUUiCk..',
    '.Z^UuUnuUUUiCk..',
    '.Z^UuUXXXUiCUuk.',
    '.ZhUunnjjniCUuk.',
    '.ZhUuUUUUiCUhuk.',
    '.uuUUXXUUiCUUuk.',
    '..uUXXUUUCUUZZuk',
    '..knuuUUUUuUZuk.',
    '...uUUUk.uUUUk.k',
    '...uUUUk.uUUUk..',
    '...qjqqk.qjqqk..',
    '...qjqqk.qjqqk..',
    '...qjjjk.qjjjk..',
    '...kkkkk.kkkkk..',
    '....nnnnnnnnn...',
  ],
  player_up_2: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXUUuUUuk.yk.',
    '...uXUUuUUukjYk.',
    '...uXUUuUUukYyYk',
    '...uXUUuUUukiC..',
    '...uuuUuUUUkiC..',
    '.ZZ^^^nuUUUiCk..',
    '.Z^UuUnuUUUiCk..',
    '.Z^UuUXXXUiCUuk.',
    '.ZhUunnjjniCUuk.',
    '.ZhUuUUUUiCUhuk.',
    '.uuUUXXUUiCUUuk.',
    '.uuUXXUUUCUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '...uUUUk..uUUUk.',
    '...qjqqk..uUUUk.',
    '...qjqqk..uUUUk.',
    '...qjqqk..qjqqk.',
    '...qjjjk..qjqqk.',
    '...kkkkk..qjjjk.',
    '....nnnn..kkkkk.',
  ],
  player_up_3: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXUUuUUuk.yk.',
    '...uXUUuUUukjYk.',
    '...uXUUuUUukYyYk',
    '...uXUUuUUukiC..',
    '...uuuUuUUUkiC..',
    '.ZZ^^^nuUUUiCk..',
    '.Z^UuUnuUUUiCk..',
    '.Z^UuUXXXUiCUuk.',
    '.ZhUunnjjniCUuk.',
    '.ZhUuUUUUiCUhuk.',
    '.uuUUXXUUiCUUUuk',
    '..uUXXUUUCUUUZuk',
    '..knuuUUUUuUZZk.',
    '...uUUUk.uUUUk.k',
    '...uUUUk.uUUUk..',
    '...uUUUk.uUUUk..',
    '...qjqqk.qjqqk..',
    '...qjqqk.qjqqk..',
    '...qjjjk.qjjjk..',
    '....kkkkkkkkk...',
  ],
  // side = nach rechts; Schwert locker in der vorderen Hand
  player_side_0: [
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2khk..',
    '..uXUUUuun22hhk.',
    '..uXUUUuun22nk..',
    '..uuXUUuuuu2k...',
    '.uXUXXUUUUUuk...',
    '.uXUuUXXUUUuk...',
    '.uXUuUXXXUUuk...',
    '.uXUuUUUUUhYiiiI',
    '.uXUuUUUUUUhuk..',
    'uuXUUXXUUUU2uk..',
    'uuuUUUUUUUUUuk..',
    'knuuUUUUUUUuk...',
    '..uUUUk.uUUUk...',
    '.uUUUk...uUUUk..',
    '.qjqqk...qjqqk..',
    'qjqqk.....qjqqk.',
    'qjjjk.....qjqqk.',
    'kkkkk.....qjjjk.',
    'nnnn.......kkkkk',
  ],
  player_side_1: [
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2khk..',
    '..uXUUUuun22hhk.',
    '..uXUUUuun22nk..',
    '..uuXUUuuuu2k...',
    '.uXUXXUUUUUuk...',
    '.uXUuUXXUUUuk...',
    '.uXUuUXXXUUuk...',
    '.uXUuUUUUUhYiiiI',
    '.uXUuUUUUUUhuk..',
    'uuXUUXXUUUU2uk..',
    'uuuXUUUUUUUUUuk.',
    'knuuUUUUUUUUuk..',
    '...uUUUkuUUUk...',
    '...uUUUkuUUUk...',
    '...qjqqkqjqqk...',
    '...qjqqkqjqqk...',
    '...qjjjkqjjjk...',
    '...kkkkkkkkkk...',
    '....nnnnnnnn....',
  ],
  player_side_2: [
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2khk..',
    '..uXUUUuun22hhk.',
    '..uXUUUuun22nk..',
    '..uuXUUuuuu2k...',
    '.uXUXXUUUUUuk...',
    '.uXUuUXXUUUuk...',
    '.uXUuUXXXUUuk...',
    '.uXUuUUUUUhYiiiI',
    '.uXUuUUUUUUhuk..',
    'uuXUUXXUUUU2uk..',
    'uuuUUUUUUUUUuk..',
    'knuuUUUUUUUuk...',
    '..uUUUk.uUUUk...',
    '..uUUUk...uUUUk.',
    '..qjqqk...qjqqk.',
    '.qjqqk.....qjqqk',
    '.qjqqk.....qjjjk',
    '.qjjjk.....kkkkk',
    '.kkkkknn...nnnn.',
  ],
  player_side_3: [
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2khk..',
    '..uXUUUuun22hhk.',
    '..uXUUUuun22nk..',
    '..uuXUUuuuu2k...',
    '.uXUXXUUUUUuk...',
    '.uXUuUXXUUUuk...',
    '.uXUuUXXXUUuk...',
    '.uXUuUUUUUhYiiiI',
    '.uXUuUUUUUUhuk..',
    'uuXUUXXUUUUU2uk.',
    'uuuXUUUUUUUUUuk.',
    'knuuUUUUUUUUuk..',
    '...uUUUkuUUUk.uk',
    '...uUUUkuUUUk...',
    '...uUUUkqjqqk...',
    '...qjqqkqjqqk...',
    '...qjqqkqjjjk...',
    '...qjjjkkkkkk...',
    '...kkkkknnnn....',
  ],
  // Angriff: Ausfallschritt, Klinge stößt nach unten an der rechten Seite
  player_attack_down: [
    '................',
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk....',
    '...uX22222uk....',
    '...uXhkhk2uk....',
    '...uXhh222uuk...',
    '...uuu222uUUuk..',
    '.ZZ^^^^UUUUUUuk.',
    '.Z^UuUXXUUUUhYk.',
    '.Z^UuUXXXUUUuyYk',
    '.ZhUunnjjnnUukiI',
    '.ZhUuUUUUUUUukCi',
    '.uuUUXXUUUUUuk.i',
    '.uuUXXUUUUUUk..i',
    '.knuuUUUUUuk...i',
    '.uUUUk..uUUUk..C',
    '.uUUUk..uUUUk...',
    '.qjqqk..uUUUk...',
    '.qjjjk..qjqqk...',
    '.kkkkk..qjqqk...',
    '..nnn...qjjjkn..',
  ],
  // Angriff nach oben: Klinge über dem Kopf, Ausfallschritt nach hinten
  player_attack_up: [
    '..............I.',
    '..............i.',
    '.....__.......i.',
    '....ZZXuk.....i.',
    '...Z^^XUUuk...i.',
    '...ZXXUUUXuk..i.',
    '...uXUUuUUukjYy.',
    '...uXUUuUUukyYk.',
    '...uXUUuUUuhkk..',
    '...uuuUuUUU2k...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnnnnUUuk..',
    '.ZhUuUUUUUUUuk..',
    '.uuUUXXUUUUUUuk.',
    '.uuUXXUUUUUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '..qjqqk..uUUUk..',
    '..qjqqk..uUUUk..',
    '..qjjjk..qjqqk..',
    '..kkkkk..qjqqk..',
    '...nnn...qjjjk..',
    '.........kkkkkn.',
  ],
  // Angriff seitlich: tiefer Ausfallschritt, gestreckter Arm, lange Klinge
  player_attack_side: [
    '................',
    '................',
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2knk..',
    '..uXUUUuun2hhhk.',
    '..uuXUUuun22k...',
    '.uXUXXUUUuu2uk..',
    '.uXUuUXXUUUUuk..',
    '.uXUuUXXXUUUhYiI',
    'uuXUuUUUUUUUuykk',
    'uuXUuUUUUUUUhuk.',
    'uuuXUUXXUUUU2uk.',
    'uuuXUUUUUUUuk...',
    'knuuUUUUUUuk....',
    '..uUUUk.uUUUk...',
    '.uUUUk....uUUUk.',
    '.qjqqk.....uUUUk',
    'qjqqk......qjqqk',
    'qjjjk......qjqqk',
    'kkkkknn....qjjjk',
  ],
  // Held stirbt: sackt in die Knie (Augen zu), dann liegend im Umhang
  player_die_0: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX2kk22ukjYk.',
    '...uuu2222ukYyYk',
    '.ZZ^^^^UUUUUuik.',
    '.Z^UuUXXUUUUukC.',
    '.Z^UuUXXXUUUuk..',
    '.ZhUuUUUUUUUuk..',
    '.ZhUuUUUUUUUuk..',
    '.uuUUXXUUUUUUuk.',
    '.uuUXXUUUUUUZuk.',
    'ZuknuuUUUUUuUZk.',
    '.uuknuUUUUUuZZk.',
    '..kkkUUUkkUUUkk.',
    '...nnnnnnnnnnn..',
  ],
  player_die_1: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...........YiiiI',
    '..........yk....',
    '....__.....k....',
    '..Z^^XXuk.......',
    '.ZXXXUUUUuuk....',
    '.ZXU2kk2UUUUuk..',
    '.uXU22222UUUUuk.',
    '.uuXUUUUUUUUUZuk',
    '..uknuuUUUuuUZuk',
    '...kkkkkkkkkkkk.',
  ],
  // Skelett 16x16 (GP7-CH-2 Phase 1, Zeichner A): AUFRECHT-SCHMAL, Wertstufe
  // HELL. EIGENE Knochenrampe: " Schatten kalt 88,2 | $ Mitte 124,0 |
  // / Licht warm 154,1 — die Bestandsrampe O/B/b/N ist verlassen (sie gehoert
  // Bran/Hedda/Warden, CH-1-Kopplung). Outline flip-neutral: OBEN Rim '_' bzw.
  // Licht, SEITEN die Mittelstufe auf BEIDEN Seiten gleich, UNTEN 'k';
  // Augenhoehlen, Rippenfenster und Beckenkerbe sind das einzige Innen-Schwarz.
  // Pose: nach links geneigter Schaedel ueber mittigem Rumpf, RECHTER Arm
  // erhoben, LINKER haengend, Schrittstellung — das bricht die Spiegelgleich-
  // heit (96,1 -> 63,7) und traegt mit den Beinen drei Lauf-Zeilenbaender.
  // BEFUND der Bild-Schleifen: der kalte Schattenton liest neben hellem
  // Knochen als BLAU — deshalb nur im *_die-Haufen als Kantenschatten.
  skeleton_0: [
    '.....__.........',
    '...///////..__..',
    '.../kk//k/../_..',
    '....//k//...//..',
    '.....$$.....$$..',
    '...__///___$$...',
    '...$/.$/////....',
    '...$/.$/kk$/....',
    '...$/.$///$/....',
    '...$/.$//k//....',
    '...$$..$$$$.....',
    '......$$//$$....',
    '....../$..$/....',
    '....../$..$/....',
    '....../$..$/....',
    '......$$..$$....',
  ],
  skeleton_1: [
    '.....__.........',
    '...///////......',
    '.../kk//k/..__..',
    '....//k//...//..',
    '.....$$.....$$..',
    '...__///___$$...',
    '...$/.$/////....',
    '...$/.$/kk$/....',
    '...$/.$///$/....',
    '...$/.$//k//....',
    '.......$$$$.....',
    '......$$//$$....',
    '.....$/....$/...',
    '.....$/....$/...',
    '.....$/....$/...',
    '.....$$....$$...',
  ],
  skeleton_die: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...___..........',
    '..$/////........',
    '..$kk//$..__....',
    '..$""/$$//////$.',
    './/////$$////$$$',
    '//////$$$/////$$',
    '.$$//$$//$$$$//.',
    '..$kkkkkkkkkkk..',
  ],
  // GHUL 16x20 (GP7-CH-2 Phase 1, FIX 1). Familie AUFRECHT-MASSIG, MITTEL.
  // Blind-Juror 2 hielt die Vorfassung fuer das SKELETT ('schmaler Knochen-
  // koerper, helle Klinge waagerecht ueber den Schultern') — der 8-Texel-Rim-
  // Balken war die 'Klinge'. FIX 1: (a) Rim in 2-3-Texel-SEGMENTE gebrochen
  // (Schaedeldecke, linke Buckelspitze, rechte Buckelspitze; kein Lauf > 3),
  // (b) GROSSER bleicher Schaedel als Identitaet: H/3 steigt bis in die
  // Buckelsenke (Zeile 0) und ist 7 statt 5 Texel breit, dunkle Augenhoehlen
  // (Fable-Ausnahme: Ghul-Schaedel = 2-Stufen-Akzentflaeche, G7 deklariert).
  // Silhouette unveraendert: Buckel ist die BREITESTE Stelle und sitzt oben,
  // UNGLEICH (links hoeher/bis Spalte 0, rechts tiefer und abgeschraegt),
  // kein Hals, Arme haengen FREI mit Luecke. Lumpen-Rampe d / < / > ('g' raus).
  // 'C' bleibt als waagerechter Nasenschatten (check_gfx6_art:200).
  // FIX 1b (Knaeuel-Kanten): die Aussenspalten der beiden Arme sind UNGLEICH —
  // linker Arm '<' (L 119), rechter Arm 'd' (L 84). Zwei benachbarte Ghule
  // beruehren sich damit mit dL 35 statt 0 und trennen sich im Knaeuel.
  ghoul_0: [
    '|||>>.H||H......',
    '>>ddd33HHH.d|||.',
    '<dddHHHHHHdd<ddd',
    '<<ddHkHHkHHdddd.',
    '.<ddHHCCHHHd<<..',
    '..dkHHHHHkdd<...',
    '||dddk33HHkd|||.',
    '.ddd.kddddk.>><.',
    '.kdd.d<<<<d..<<k',
    '.kdd.dd<<dd..<<k',
    '.kdd.dd<<dd..<<k',
    '.kdd.dd<<dd..<<k',
    '.k>d.dddddd.....',
    '.k>d.dddddd.....',
    '.k>>.kddddk.....',
    '....kddddddk....',
    '....kddk.kddk...',
    '....kddk.kddk...',
    '...kdddk.kdddk..',
    '...kdddk........',
  ],
  // Zweiter Gang: der Ghul SCHLURFT — Buckel und Schaedel sacken eine Spalte
  // nach rechts, die Arme tauschen die Laenge, das Standbein wechselt.
  ghoul_1: [
    '.|||>>.H||H.....',
    '.>>ddd33HHH.d|||',
    '.<dddHHHHHHdd<dd',
    '.<<ddHkHHkHHddd.',
    '..<ddHHCCHHHd<..',
    '...dkHHHHHkdd...',
    '.||dddk33HHkd|||',
    '.ddd.kddddk.>><.',
    '.k>d.d<<<<d..<<k',
    '.kdd.dd<<dd..<<k',
    '.kdd.dd<<dd..<<k',
    '.k>>.dd<<dd..<<k',
    '.....dddddd..ddk',
    '.....dddddd..d>k',
    '.....kddddk..>>k',
    '....kddddddk....',
    '..kddk...kddk...',
    '..kddk....kddk..',
    '.kdddk....kdddk.',
    '..........kdddk.',
  ],
  // Sterben Stufe 1, FIX 1: flacher, einseitiger Haufen mit KANTENTOENEN —
  // drei Konturtoene (< / d / k) mit je >= 8 Texeln, Ton-Spiegel 35 statt 73,
  // bleicher Schaedel liegt frei, Bodenkante aus 'k'.
  ghoul_die: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...||<<HH<<>>...',
    '.||HH33HHH>><<dd',
    'kdd<<dd<<>><<>>k',
    'kkddddkkdd<<<<kk',
  ],
  // Schwert-Schwünge: Stahlbogen mit hellem Blitz
  sword_slash_down: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.C..............',
    'CiC............C',
    '.iiC..........CC',
    '..iiC........Cii',
    '...iiCC....CCii.',
    '....IiiCCCCiii..',
    '.....IIiiiiiI...',
    '......IIIIII....',
    '................',
  ],
  sword_slash_up: [
    '................',
    '......IIIIII....',
    '.....IIiiiiiI...',
    '....IiiCCCCiii..',
    '...iiCC....CCii.',
    '..iiC........Cii',
    '.iiC..........CC',
    'CiC............C',
    '.C..............',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  sword_slash_side: [
    '................',
    '.......C........',
    '......CiC.......',
    '.......iiC......',
    '........iiC.....',
    '.........IiC....',
    '.........IiiC...',
    '..........IiC...',
    '..........IiC...',
    '.........IiiC...',
    '.........IiC....',
    '........iiC.....',
    '.......iiC......',
    '......CiC.......',
    '.......C........',
    '................',
  ],
  coin_0: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '......kkkk......',
    '.....kyyyYk.....',
    '....kybyyYYk....',
    '....kybyyYYk....',
    '....kyyyyYYk....',
    '.....kyYYYk.....',
    '......kkkk......',
    '................',
    '................',
    '................',
    '................',
  ],
  coin_1: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......kk.......',
    '......kyYk......',
    '......kbYk......',
    '......kyYk......',
    '......kyYk......',
    '......kyYk......',
    '.......kk.......',
    '................',
    '................',
    '................',
    '................',
  ],
  // Zerschlagbare Props: Ton-Vase und Stein-Urne (AABB 12x12)
  vase: [
    '................',
    '................',
    '......kkk.......',
    '.....kJQqk......',
    '......kQk.......',
    '.....kJQqk......',
    '....kJJQQqk.....',
    '...kJJQQQjqk....',
    '...kJQQQQjqk....',
    '...kQQQQQjqk....',
    '...kQQQjjqqk....',
    '....kQQjjqk.....',
    '.....kjqqk......',
    '.....kkkkk......',
    '................',
    '................',
  ],
  urn: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kDDLLTTk....',
    '.....kkkkkk.....',
    '.....kDLLTk.....',
    '....kDDLLTTk....',
    '...kDDLLLTTtk...',
    '...kDLLLLTTtk...',
    '...kLLLLTTttk...',
    '...kLLLTTtttk...',
    '....kLLTTttk....',
    '.....kLTttk.....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  // GFX4 (§3.5b): gebackene '0'-Kontaktschatten bei vase/urn/chest ENTFERNT —
  // der Engine-Pass (§2.4 drawSoftShadow fuer echte Props) uebernimmt sie.
  // Scherben-Animation (generisch für Vase und Urne)
  prop_break_0: [
    '................',
    '................',
    '................',
    '....kb...Bk.....',
    '...kBk..kbk.....',
    '................',
    '..kQk.....kTk...',
    '.....kBbk.......',
    '....kbBBbk......',
    '.....kBbk.......',
    '..kTk.....kQk...',
    '................',
    '...kbk...kBk....',
    '....kB...bk.....',
    '................',
    '................',
  ],
  prop_break_1: [
    '................',
    '..b..........B..',
    '................',
    '.....k....k.....',
    '.B............b.',
    '................',
    '................',
    '.......bB.......',
    '................',
    '................',
    '.b............B.',
    '.....k....k.....',
    '................',
    '..B..........b..',
    '................',
    '................',
  ],
  // Schatztruhe: Holz mit Beschlägen, Gold-Schimmer im Spalt
  chest_closed: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kQJQQQQQQQJQQk.',
    '.kQYQQQQQQQQYQk.',
    '.kQYQQQkkQQQYQk.',
    '.kkkkkyy1ykkkkk.',
    '.kqYqqqkkqqqYqk.',
    '.kqYqjqqqqjqYqk.',
    '.kqqqqqqqqqqqqk.',
    '.kqYqjqqqqjqYqk.',
    '.kqqqqqqqqqqqqk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  chest_open: [
    '..kkkkkkkkkkkk..',
    '.kqqqqqqqqqqqqk.',
    '.kqQQJQQQQJQQqk.',
    '.kkkkkkkkkkkkkk.',
    '.kyyy1yyyy1yyyk.',
    '.kyYyyyYyyyYyyk.',
    '.kqYqqqqqqqqYqk.',
    '.kqYqjqqqqjqYqk.',
    '.kqqqqqqqqqqqqk.',
    '.kqYqjqqqqjqYqk.',
    '.kqqqqqqqqqqqqk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
    '................',
  ],
  // Heiltrank 10x10: leuchtend rote Flasche mit Korken
  potion: [
    '....kk....',
    '...kQQk...',
    '....kk....',
    '...k1xk...',
    '..kyxxxk..',
    '.koxxxxRk.',
    '.kxxxxRRk.',
    '.kxxRRRrk.',
    '..kkkkkk..',
    '..........',
  ],
  // Nebelschwade 32x16: EIN Grauton, weich auslaufende Ellipse
  fog_blob: [
    '................................',
    '............ffffff..............',
    '........ffffffffffff............',
    '.....ffffffffffffffffff.........',
    '...ffffffffffffffffffffffff.....',
    '..ffffffffffffffffffffffffffff..',
    '.ffffffffffffffffffffffffffffff.',
    '.ffffffffffffffffffffffffffffff.',
    '..ffffffffffffffffffffffffffff..',
    '...ffffffffffffffffffffffff.....',
    '.....ffffffffffffffff...........',
    '........ffffffff.......ffff.....',
    '..........ffff.........ff.......',
    '................................',
    '................................',
    '................................',
  ],
  // HUD-Herzen 8x8
  // GFX4 (§3.5c): 1px Innen-Highlight. heart_full = heller Rot-Glanz 'x' oben-
  // links (+ Bestands-'b'-Schimmer), heart_empty = kuehler Grau-Glanz 'S'.
  heart_full: [
    '.kk..kk.',
    'kxxkkRRk',
    'kxRRRRrk',
    'kRRRRrrk',
    '.kRRrrk.',
    '..kRrk..',
    '...kk...',
    '........',
  ],
  heart_empty: [
    '.kk..kk.',
    'kggkkggk',
    'kgSnnngk',
    'kgnnnngk',
    '.kgnngk.',
    '..kgnk..',
    '...kk...',
    '........',
  ],
  // Grufthund 16x12 (GP7-CH-2 Phase 1, Zeichner A): VIERBEINER, Wertstufe
  // DUNKEL. Die Erdrampe z/p/v/P/V ist VOLLSTAENDIG verlassen (V3/Sperrliste);
  // eigene Petrol-Rampe (92,1 / 105,2 / 123,8), als WERT-BAENDER gesetzt: je
  // Zeile eine Stufe, nie zwei Nachbarstufen gedithert (die drei Toene liegen
  // farblich nur 6,49 dE00 auseinander). Rim kalt '|' als EINE Texelzeile auf
  // Rueckenkamm und Schaedeloberkante (flip-neutral). Rippenpaar = Skelett-
  // Mitte (nicht 'b': 'b' liest als weisses Etikett und hebt das Koerper-L).
  // Merkmal: EIN Texel Seelenglut '8' als Auge. Pose V3: Ruecken hoch,
  // Schaedeloberkante zwei Zeilen tiefer, Schnauze nach vorn-unten, Schwanz
  // freistehend hinten-oben, Bauch hinter dem Brustkorb hochgezogen. Auf dem
  // GRAVEYARD-Weg traegt ihn der FARB-Pfad: dE00 31,1 (dL nur +3,7).
  // Blick nach rechts, main.js spiegelt.
  hound_0: [
    '.``.............',
    '.```............',
    '.``||||||``}....',
    '.}}}}}}}}$$}}...',
    '..{{{{{{{{{{|||.',
    '..{{{{{{{{{}}8`.',
    '..{{{..{{{{{}}``',
    '..}k}...}k}..kk.',
    '..}k}...}k}.....',
    '..{k{...{k{.....',
    '..{k{...{k{.....',
    '..kkk...kkk.....',
  ],
  hound_1: [
    '``..............',
    '```.............',
    '.``||||||``}....',
    '.}}}}}}}}$$}}...',
    '..{{{{{{{{{{|||.',
    '..{{{{{{{{{}}8`.',
    '..{{{..{{{{{}}``',
    '.}k}....}k}..kk.',
    '.}k}....}k}.....',
    '.{k{.....{k{....',
    '.{k{.....{k{....',
    '.kkk.....kkk....',
  ],
  // Telegraph: geduckt, 2 px flacher und laenger, Laeufe gespannt
  hound_telegraph: [
    '................',
    '................',
    '................',
    '.``.............',
    '.``||||||``}....',
    '.}}}}}}}}$$}}...',
    '..{{{{{{{{{{|||.',
    '..{{{{{{{{{}}8`.',
    '..{{{..{{{{{}}``',
    '..{k{...{k{..kk.',
    '..{k{...{k{.....',
    '..kkk...kkk.....',
  ],
  // Leap: gestreckt in der Luft, Laeufe vor und zurueck
  hound_leap: [
    '``..............',
    '``..............',
    '```|||||```}....',
    '.}}}}}}}}}}}}}..',
    '.{{{{{{{{$${|||.',
    '.{{{{{{{{{{}}8`.',
    '}}{{{...{{{{}}``',
    'k}}.......{{{kk.',
    'kk.........}}}..',
    '...........kkk..',
    '................',
    '................',
  ],
  // Down: liegt flach auf dem Bauch, Laeufe gespreizt, verwundbar
  hound_down: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.``.............',
    '.``||||||``}}...',
    '.`}}}}}}}$$}``..',
    '.{{{{{{{{{{{||||',
    '{{{{{{{{{{{}}8``',
    'kkkkk..kkkkkkkk.',
  ],
  // Tot: auf dem Ruecken, Laeufe nach oben, Auge zu
  hound_die: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..}}}..{{{......',
    '..}k}..{k{......',
    '..}k}..{k{......',
    '.``||||||``}....',
    '.}}$$}}}}}}}....',
    '.{{{{{{{{{{{||`.',
    '.kkkkkkkkkk}}8`.',
  ],
  // ROSTPANZER 20x18 (GP7-CH-2 Phase 1, FIX 1). Familie AUFRECHT-BREIT,
  // Wertstufe DUNKEL. Signatur: winziger Helm (Zeilen 0-2), dann ein abrupter
  // Plattenschelf — Ausladung in den Spalten 0-2 / 17-19 OBERHALB Zeile 6
  // (E-B9/P4). Schild-Landezone (Spalten 13-18, Zeilen 6-15) traegt nur den
  // Schildarm; dort liegt shield_side (enemies.js:642-656, Versatz 13/4).
  // FIX 1 (E-B9 fuer den Rost NEU): KEIN '|' mehr — die drei Cyan-Bloecke lasen
  // als Frost/Schnee und rueckten ihn optisch an den Torwaechter. Rim jetzt
  // '_' als 2-Texel HARTER Glanzpunkt NUR auf der Helmkuppe (Zeile 0) plus '6'
  // (hellste eigene Rampenstufe) als WEICHE Lichtkante auf den Plattenober-
  // kanten (Anker-Regel 7). Rampe Rost 4/5/6 BEHALTEN (Schrittmass 1,06;
  // ortsgetrennt exklusiv zum Torwaechter im DORF, V5). Knochen nur als Kiefer-
  // und Rippenlinie (b/B). 'y' = Augenglut/Nieten als art:'merkmal'.
  rust_0: [
    '........6__6........',
    '......4666664.......',
    '......46ynny4k......',
    '......k4bbbb4k666655',
    '.6666654BBBB4k556654',
    'k5665555555544556654',
    'k5555555666654555554',
    '..k454k5bbbb5k55554k',
    '..k454k566665k.k454k',
    '..k454k554455k.k454k',
    '..k44kk4y55y4k.k454k',
    '.....k5555554k.k454k',
    '....k5555kk554k444k.',
    '....k455k.k554k44k..',
    '....k455k.k554k.....',
    '...k455k..k5554k....',
    '..k44554k.k4444k....',
    '..k44444k...........',
  ],
  // Zweiter Gang: der Panzer STAMPFT — Helm und Platten sacken eine Zeile ab,
  // die Schrittfolge kehrt sich um, der kurze Arm wechselt die Seite.
  rust_1: [
    '....................',
    '........6__6........',
    '......4666664.......',
    '......46ynny4k666655',
    '.6666654bbbb4k556654',
    'k56655k4BBBB4k556654',
    'k5555555555544555554',
    '..k4545566665555554k',
    '..k454k5bbbb5k.k454k',
    '..k454k566665k.k454k',
    '..k454k454455k.k44k.',
    '..k44kk4y55y4k......',
    '.....k4555554k......',
    '.....k555k.k4555k...',
    '.....k455k.k455k....',
    '.....k455k.k455k....',
    '.....k444k..k455k...',
    '...........k45554k..',
  ],
  // Sterben Stufe 1: der Panzer kippt zur Schildseite weg. Glanz warm ('_'),
  // Plattenkanten '6'; beide Halbseiten tonlich ausgeglichen (R-B4).
  rust_die: [
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '...............6__..',
    '.............66554k.',
    '..........6655544k44',
    '......k655655444k4..',
    '....k6556655445k44..',
    '..kk5545556655k4kk..',
  ],
  // Schild-Overlays (Requisit des Rostpanzers; Groesse FEST 6x12 / 12x6).
  // FIX 1: '6'-Lichtkante statt '|', dazu 2 Texel '_' Glanz auf der Oberkante.
  // Seitenlicht bleibt (R-B4).
  shield_side: [
    '66__66',
    'k65546',
    'k6y546',
    'k65546',
    'k65546',
    'k55544',
    'k5y544',
    'k55444',
    'k55444',
    'k54444',
    'k44444',
    '.4444.',
  ],
  shield_up: [
    '.66__666666.',
    'k66555555544',
    'k6y555555y44',
    'k66555554444',
    'k44444444444',
    '.kkkkk44444.',
  ],
  shield_down: [
    '.666__66666.',
    'k66655555544',
    'k66y5555y444',
    'k66655554444',
    'k45444444444',
    '.kkkkk44444.',
  ],
  // Funkenstern 8x8 beim Block
  block_spark: [
    '...y....',
    '.o.1.o..',
    '..y1y...',
    'y11111y.',
    '..y1y...',
    '.o.1.o..',
    '...y....',
    '........',
  ],
  // Knochen-Bumerang 10x10, 2 Rotationsphasen (um 90 Grad gedreht)
  boomerang_0: [
    '..kkkkkk..',
    '.kNNbbbbk.',
    '.kbbBBbbk.',
    '..kkkkbBk.',
    '.....kbBk.',
    '.....kbBk.',
    '.....kbOk.',
    '.....kbOk.',
    '.....kkOk.',
    '......kk..',
  ],
  boomerang_1: [
    '......kk..',
    '.....kkOk.',
    '.....kbOk.',
    '.....kbOk.',
    '.....kbBk.',
    '.....kbBk.',
    '..kkkkbBk.',
    '.kbbBBbbk.',
    '.kNNbbbbk.',
    '..kkkkkk..',
  ],
  // Boden-Drops 10x10: Schwert, Harnisch, Ring
  item_weapon: [
    '.......kk.',
    '......kIik',
    '.....kIik.',
    '.kk.kIik..',
    'kyykiik...',
    '.kyyik....',
    '..kyyk....',
    '.kjkyk....',
    'kqjkk.....',
    '.kk.......',
  ],
  item_armor: [
    '.kkkkkkkk.',
    'kJJknnkQjk',
    'kJQQQQQQjk',
    'kJQQQQQQjk',
    '.kQbQQbjk.',
    '.kQbQQbjk.',
    '..kQQQjk..',
    '..kQQQjk..',
    '...kkkk...',
    '..........',
  ],
  item_ring: [
    '....kk....',
    '...kIik...',
    '..kkiCkk..',
    '.kykkkkYk.',
    '.kyk..kYk.',
    '.kyk..kYk.',
    '..kykkYk..',
    '...kyYk...',
    '....kk....',
    '..........',
  ],
  // Glitzer-Overlay 8x8 fuer seltene Drops
  sparkle_0: [
    '........',
    '...I....',
    '...N....',
    '.INNNI..',
    '...N....',
    '...I....',
    '........',
    '........',
  ],
  sparkle_1: [
    '...I....',
    '...I....',
    '.I.N.I..',
    'IINNNII.',
    '.I.N.I..',
    '...I....',
    '...I....',
    '........',
  ],
  // Inventar-Icons 12x12 (auch abgedunkelt als Geister-Slots nutzbar)
  icon_weapon: [
    '.....kk.....',
    '....kIik....',
    '....kIik....',
    '....kIik....',
    '....kIik....',
    '....kiCk....',
    '..kkkiCkkk..',
    '.kyyYkkYyyk.',
    '....kjqk....',
    '....kjqk....',
    '....kyYk....',
    '.....kk.....',
  ],
  icon_armor: [
    '.kkk....kkk.',
    'kJJJkkkkQQjk',
    'kJJQQQQQQQjk',
    'kJQQQQQQQQjk',
    '.kQQQQQQQjk.',
    '.kQbQQQQbjk.',
    '.kQbQQQQbjk.',
    '..kQQQQQjk..',
    '..kQQQQQjk..',
    '..kkkkkkkk..',
    '............',
    '............',
  ],
  icon_ring: [
    '.....kk.....',
    '....kIik....',
    '...kkiCkk...',
    '..kyykkyYk..',
    '.kyk....kYk.',
    '.kyk....kYk.',
    '.kyk....kYk.',
    '..kyk..kYk..',
    '...kyyYYk...',
    '....kkkk....',
    '............',
    '............',
  ],
  // HUD-Icon 16x16: Knochen-Bumerang gross
  icon_boomerang: [
    '....kkkkkkkk....',
    '...kNNbbbbbbk...',
    '..kNbbbbBBbbbk..',
    '..kbbkkkkkbBbk..',
    '..kkk....kbBbk..',
    '..........kbBk..',
    '..........kbBk..',
    '..........kbBk..',
    '..........kbOk..',
    '..........kbOk..',
    '..........kbOk..',
    '..........kkOk..',
    '...........kOk..',
    '...........kkk..',
    '................',
    '................',
  ],
  // GRABWAECHTER (Boss) 24x32: Skelett-Koloss im Grabschleier, korrodierte
  // Pauldrons (Rost 4/5/6), gruene Seelenglut (7/8) in den Augen, Zweihaender
  // (Klinge C/i/I, Griff Y/y). Silhouetten je Zustand klar unterscheidbar
  // (3-Kanal-Telegraphie: Form + Helligkeit + Bewegungsstopp). Blick nach unten,
  // main.js spiegelt fuer den Sturm (Flip-Key am Listenende).
  // idle: aufrecht, Zweihaender vor dem Koerper in den Boden gestuetzt.
  warden_idle: [
    '.......|........|.......',
    '......|8|......|8|......',
    '.....|86k.7887.k68|.....',
    '....|k6b7bbNNbb7b6k|....',
    '...|647bbbbbbbbbbb744|..',
    '..|6BBbbbbbbbbbbbbBB4k..',
    '..k6Bb7788bbbb8877bB4k..',
    '..k6Bb7888bbbb8887bB4k..',
    '..k5Bbb77bbbbbb77bbB4k..',
    '...kBbbbbOObbOObbbBBk...',
    '...kkBbbbObbbbObbBBkk...',
    '..|64kBbbkOnnOkbBk44k...',
    '.k6554kkkkkkkkkkk5544k..',
    'k65554kBbbYYYYbbBk55444k',
    'k6554UukbbYyyYbbkuU5544k',
    '.kUUuuBBbkiCCikbBBuuUk..',
    '..kuuUBBBbkiikbBBBUuuk..',
    '..kuXUUBObBiCibBOBUUXuk.',
    '..kuXXUUBBBiCiBBBUUXXuk.',
    '...kuXXUBOBiCiBOBUXXuk..',
    '...kuuXXBBBiCiBBBXXuuk..',
    '....kuuXBOBiIiBOBXuuk...',
    '....kOBBBBBiCiBBBBBOk...',
    '...kOBOBkBBiCiBBkOBOk...',
    '...kBBOk.kBiCiBk.kOBBk..',
    '..kBBBk..kBiIiBk..kBBBk.',
    '..kOBk...kBiCiBk...kBOk.',
    '..kBBk...kBiCiBk...kBBk.',
    '..kkk....kkiIikk....kkk.',
    '.........kBiCiBk........',
    '.........kkiCikk........',
    '..........kkkkk.........',
  ],
  // walk_0/1: langsamer Stalk-Gang, Klinge geschultert, Beine wechseln
  warden_walk_0: [
    '.......|........|.......',
    '......|8|......|8|......',
    '.....|86k.7887.k68|.....',
    '....|k6b7bbNNbb7b6k|....',
    '...|647bbbbbbbbbbb744k..',
    '..k6BBbbbbbbbbbbbbBB4k..',
    '..k6Bb7788bbbb8877bB4k..',
    '..k6Bb7888bbbb8887bB4k..',
    '..k5Bbb77bbbbbb77bbB4k..',
    '...kBbbbbOObbOObbbBBk...',
    '...kkBbbbObbbbObbBBkk...',
    '..k64kBbbkOnnOkbBk44k...',
    '.k6554kkkkkkkkkkk5544k..',
    'k65554kBbbbbbbbBk655444.',
    'k6554UukbbbbbbbkuU65544.',
    '.kUuuBBBbbbbbbbBBuuUk...',
    '..kuuUUBBbbbbbbBBUUuuk..',
    '..kuXUUUBOBBBBOBUUUXuk..',
    '..kuXXUUBBBBBBBBUUXXuk..',
    '...kuXXUBOBBBBOBUXXuk...',
    '...kuuXXBBBBBBBBXXuuk...',
    '....kuuXXBOBBOBXXuuk....',
    '.....kOBBBBBBBBBBOk.....',
    '....kBBOk...kOBk........',
    '...kOBBk....kBBk........',
    '...kBBk.....kkk.........',
    '..kOBk..................',
    '..kBbk..................',
    '..kkk...................',
    '........................',
    '........................',
    '........................',
  ],
  warden_walk_1: [
    '.......|........|.......',
    '......|8|......|8|......',
    '.....|86k.7887.k68|.....',
    '....|k6b7bbNNbb7b6k|....',
    '...|647bbbbbbbbbbb744k..',
    '..k6BBbbbbbbbbbbbbBB4k..',
    '..k6Bb7788bbbb8877bB4k..',
    '..k6Bb7888bbbb8887bB4k..',
    '..k5Bbb77bbbbbb77bbB4k..',
    '...kBbbbbOObbOObbbBBk...',
    '...kkBbbbObbbbObbBBkk...',
    '..k64kBbbkOnnOkbBk44k...',
    '.k6554kkkkkkkkkkk5544k..',
    'k65554kBbbbbbbbBk655444.',
    'k6554UukbbbbbbbkuU65544.',
    '.kUuuBBBbbbbbbbBBuuUk...',
    '..kuuUUBBbbbbbbBBUUuuk..',
    '..kuXUUUBOBBBBOBUUUXuk..',
    '..kuXXUUBBBBBBBBUUXXuk..',
    '...kuXXUBOBBBBOBUXXuku..',
    '..ukuuXXBBBBBBBBXXuuk...',
    '...uuuuXXBOBBOBXXuuuu...',
    '.....kOBBBBBBBBBBOk.....',
    '........kOBk...kBBOk....',
    '........kBBk...kOBBk....',
    '........kkk....kBBk.....',
    '...............kOBk.....',
    '...............kBBk.....',
    '...............kkk......',
    '........................',
    '........................',
    '........................',
  ],
  // windup_a (Muster A Rundumschlag): Klinge HOCH ueber dem Kopf, Arme oben
  warden_windup_a: [
    '...........|iIi|........',
    '..........|biCib|.......',
    '.......|...kiCik...|....',
    '......|8|..kiCik..|8|...',
    '.....|86k|.kiIik.|k68|..',
    '....kk6bBbkkiCikkbBb6kk.',
    '...k44BbbbbkiCikbbbbB44k',
    '..k4BBbbbbbkiIikbbbbBB4k',
    '..k4Bb7788bbkCikb8877B4k',
    '..k4Bb7888bbbbbbb8887B4k',
    '..k4Bbb77bbbbbbbb77bbB4k',
    '...kBbbbbOObbbbOObbbbBk.',
    '...kkBbbbObbbbbbObbbBkk.',
    '..k44kBbbkkbbbbkkbBk44k.',
    '.k4556kkkYYYYYYkkk6554k.',
    'k45556kBbbYyyyyYbbBk6554',
    'k4556UukBBbBBBBBBBkuU654',
    '.kUUuuBBBbbBBBBBBBBuuUk.',
    '..kuuUUBObbBBBBOBUUuuk..',
    '..kuXUUUBBbBBBBBUUUXuk..',
    '..kuXXUUBOBBBBOBUUXXuk..',
    '...kuXXUBBBBBBBBUXXuk...',
    '...kuuXXBOBBBBOBXXuuk...',
    '....kOBBBBBBBBBBBBOk....',
    '...kOBOBk.kkkk.kOBOk....',
    '...kBBOk..kBBBk..kOBk...',
    '..kBBBk...kOBk...kBBBk..',
    '..kOBk....kBBk....kBOk..',
    '..kBBk....kkk.....kBBk..',
    '..kkk............kkkk...',
    '........................',
    '........................',
  ],
  // windup_b (Muster B Sturm): geduckte Anlauf-Pose, Klinge weit zurueckgezogen
  warden_windup_b: [
    '....|........|..........',
    '...|8|......|8|.........',
    '..|86k.||||.k68|........',
    '.|k6BkkBNNBkkb6kk.......',
    'k44BBBBBBBBBbbbb44k.....',
    '4BBBBBBBBBBBbbbbb4k.....',
    '4Bb7788bbbb8877bb4k.....',
    '4Bb7888bbbb8887bb4k.....',
    '4Bbb77bbbbbb77bbb4k.....',
    'kBbbbbOObbOObbbbbk......',
    'kkBbbbObbbbObbbbkk......',
    'k44kBbbkbbbbkbbk44k.....',
    '4556kkkkkkkkkkk6554kkk..',
    '4556kBbbbbbbbbk6554YYYk.',
    '456UukbbbbbbbkuU6yYyyYk.',
    'kUuuBBbbbbbbbbbbiCCCCbk.',
    'kuUUBBbbbbbbbbbbiiiiik..',
    'kuXUUBOBBBBbbObUCiik....',
    'kuXXUUBBBBBBbBUUUk......',
    'kuuXXBOBBBBOBUXXuk......',
    '.kuXXBBBBBBBBXXuk.......',
    '.kOBBBBBBBBBBBBOk.......',
    'kOBOBkkkkkkkkkOBOk......',
    'kBBOk..kBBk...kOBObk....',
    'kOBk...kBBBk...kBbbBk...',
    'kBBk...kOBk.....kOBk....',
    'kkk....kBBk.....kBbk....',
    '.......kkk......kkk.....',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // dash: Sturm nach rechts, Koerper gestreckt, Klinge vorgestossen
  warden_dash: [
    '.|........|.............',
    '|8|......|8|............',
    '86k.||||.k68|...........',
    '6Bk|BNNB|kB6k|..........',
    '4BBBBBBBBBBBbb44k.......',
    'BBBBBBBBBBBBbbbb4k......',
    'b7788BBBB8877bb4k......C',
    'b7888BBBB8887bb4k....CiI',
    'bB77BBBBBB77bbb4k..CiiCi',
    'BBBBOOBBOOBBbbbkiiiiiiC.',
    'kBBBBOBBBBOBbbbYyyyyk...',
    '4kBBBkBBBBkBbkYYYYkk....',
    '56kkkkkkkkkkk6554k......',
    '56kBBBBBBBBBk65554k.....',
    '6UukBBBBBBBkuU6554k.....',
    'UuuBBBBBBBBBbbbuuU6k....',
    'uUUBBBBBBBBBbUUuuk......',
    'XUUUBOBBBBOBUUUXuk......',
    'XXUUBBBBBBBBUUXXuk......',
    'uXXUBOBBBBOBUXXuk.......',
    'uuXXBBBBBBBBXXuuk.......',
    'kOBBBBBBBBBBBbOk........',
    'kOBOBk..kkk..kbOk.......',
    'kBBBk..|OBObk.kbbk......',
    'kOBk...kBBBBk..kkk......',
    'kBBk....kOBk............',
    'kkk.....kBBk............',
    '........kkk.............',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // stuck: Klinge TIEF im Boden vorne, Boss vornuebergebeugt (Strafenfenster)
  warden_stuck: [
    '........................',
    '........................',
    '.......|........|.......',
    '......|8|......|8|......',
    '.....|86k.7887.k68|.....',
    '....|k6b7bbNNBb7b6k|....',
    '...|447bbbbbbbbbbb744|..',
    '..k4bBbb77bbbb77bbBB4k..',
    '..k4Bbb788bbbb887bbB4k..',
    '..k4Bbbb77bbbb77bbbB4k..',
    '..k4BbbbbOObbOObbbbB4k..',
    '...kBbbbbObbbbObbbbBk...',
    '..k44kBbkkbbbbkkbBk44k..',
    '.k4556kkkkkkkkkkk6554k..',
    'k45556BbbbbbbbbbBk6554k.',
    'k4556UuBBbbbbbbBBuU654k.',
    '.kUUuuUBObbbbbbOBUuuUk..',
    '..kuuUUBBbbbbbbBBUUuuk..',
    '..kuXUUBObbbYYbBOBUXuk..',
    '..kuXXUBBbBYyyYBBBUXuk..',
    '...kuXXBOBBkiCikBBOXuk..',
    '...kuuXBBBBBiCiBBBBXuk..',
    '....kOBBBBBBiIiBBBBOk...',
    '....kkOBOBBBiCiBBOBk....',
    '.....kBBOBk.iCi.kBBk....',
    '.....kOBk...iIi...kk....',
    '.....kBBk...iCi.........',
    '.....kkk...kiCik........',
    '..........kkiIikk.......',
    '..........kbiCibk.......',
    '..........kkiiikk.......',
    '...........kkkkk........',
  ],
  // summon (Ruf-Pose): beide Arme weit erhoben, Klinge in der Rechten hoch
  warden_summon: [
    '.|...............|iIi|..',
    '|8|.............|biCib|.',
    '86k.||||.|.......kiCik..',
    '6Bk|BNNB|k8|.....kiCik..',
    '4BBBBBBBBBBb.....kiIik..',
    'BBBBBBBBBBBB|....kiCik..',
    'Bb7788bbbb887|...kiCik..',
    'Bb7888bbbb8887b..kiIik..',
    'Bbb77bbbbbb77bB.bbkCikbb',
    'BbbbOObbOObbbbbbbbbbbbbb',
    'kBbbbObbbbObbbbkkkYYYYYk',
    'kkBbbkbbbbkbbkkbbYyyyyYk',
    'YYYkkkkkkkkkkYYYbbbbbbbk',
    'yYYYbbbbbbbbYYYybbbbbbbk',
    'kYYUukbbbbbkuUYYkbObbObk',
    '.kUUuBBbbbbbbbbuUUkbbbk.',
    '..kuuUBBbbbbbbUuuk.kkk..',
    '..kuXUUBOBbbbObUUXuk....',
    '..kuXXUBBBBBbbbUXXuk....',
    '...kuXXBOBBBbObXXuk.....',
    '...kuuXBBBBBbBBXuuk.....',
    '....kOBBBBBBBBBBOk......',
    '...kOBOBk.kk.kBOBOk.....',
    '...kBBOk..kk...kOBBk....',
    '..kBBBk..kOBObk.kBbBk...',
    '..kOBk...kBBbBk..kBOk...',
    '..kBBk....kOBk...kbBk...',
    '..kkk.....kBbk...kkk....',
    '..........kkk...........',
    '........................',
    '........................',
    '........................',
  ],
  // die: bricht in einen Knochenhaufen, Seelenglut erlischt (7 statt 8)
  warden_die: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '.............|..........',
    '...||......||B||........',
    '..|bb|...||bOBOb|.......',
    '.kBObbkkkkBbbbbbBk......',
    'kOb7bBBbb77bbbb7bBk.....',
    'kbb7bbbbb77bbbb77bbk....',
    'kOBbbOObbbbbbObbbbBOk...',
    '.kBObkYYkbbkYYkbbkOBk...',
    'kOBbkYyyYbkYyyYbbbkbBk..',
    'kBbbBiCCikkiCCibbBObbBk.',
    'kOBbbbiikkkkiikbbBbbbOk.',
    'kkOBBbbbBbbbBbbBBbbBBkk.',
    '.kkOBObbObbObbObbObkk...',
    '..kkbBbbkbbkbbkbBbkk....',
    '...kkOBbbbbbbbbBOkk.....',
    '....kkbBObbbbOBbkk......',
    '.....kkbbBbBBBBkk.......',
    '......kkOBBBBOkk........',
    '.......kkkkkkkk.........',
    '........................',
    '........................',
  ],
  // elite_glow 8x8 (§2.4): Glut-Augen R, Kante o. Overlay ueber Elite-Koepfen
  elite_glow: [
    '..o..o..',
    '.oRooRo.',
    'ooRRRRoo',
    '.oRooRo.',
    '..oooo..',
    '...oo...',
    '........',
    '........',
  ],
  // levelup_0/1 16x16: aufsteigender Level-Up-Ring, Gold (o/y/1) + Knochenweiss N
  levelup_0: [
    '................',
    '................',
    '................',
    '.....oyyyyo.....',
    '...oyy1NN1yyo...',
    '..oy1o....o1yo..',
    '.oy1o......o1yo.',
    '.oyo........oyo.',
    '.oyo........oyo.',
    '.oy1o......o1yo.',
    '..oy1o....o1yo..',
    '...oyy1NN1yyo...',
    '.....oyyyyo.....',
    '................',
    '................',
    '................',
  ],
  levelup_1: [
    '......NN........',
    '....oy..yo......',
    '..oy1o..o1yo....',
    '.oyo......oyo.N.',
    '.yo........oy...',
    'N1..........1N..',
    'yo..........oy..',
    'yo..........oy..',
    '.yo........oyN..',
    '.oyo......oyo...',
    '..1yo....oy1....',
    '...oy1..1yo.....',
    'N....oyyyo......',
    '.......NN.......',
    '................',
    '................',
  ],
  // icon_key 8x8: Boss-Schluessel (Gold), erscheint im HUD ab Fund
  icon_key: [
    '.kkk....',
    'kyYYk...',
    'ky1yk...',
    'kyYyk...',
    '.kyk....',
    '.kyk.kk.',
    '.kyykyk.',
    '..kkkkk.',
  ],

  // ==========================================================================
  // SLICE 6 — DIE FUENF NPCs VON GRAMFELD (16x24 = Spielermass) + Blase.
  // APPEND-ONLY ANS LISTENENDE: main.js:88 baut die Canvases in dieser
  // Objekt-Reihenfolge; check_main_slice1 und check_inventory_slice2 mappen
  // Canvas -> Sprite ueber die Erzeugungsfolge. Ein Einschub weiter oben
  // faerbt beide Alt-Tests rot.
  // ZWEI FRAMES je NPC (Muster enemies.js:628: `${kind}_0`/`_1` im 2er-
  // Umlauf fuer Stehen UND Gehen). Frame 1 senkt den Rumpf um 1 px und
  // stellt die Beine in Schritt — getrennte Walk-Grids verlangt der
  // Bestand nicht. DAZU je ein `_talk`-Sprech-Frame ganz am Listenende
  // (SPEC Rev 1 §2.1/§2.2; npcs.js:185 fragt ihn im Dialog ab).
  // SCHLUESSEL-REGEL: der Teil zwischen 'npc_' und dem Suffix ist WOERTLICH
  // die npcSpawn-id aus map_dorf.js — npcs.js baut den Schluessel daraus.
  // KLEIDERREGEL: nie u/U/X/Z (Helden-Violett) als Flaeche. Verwendet sind
  // Leder q/j/Q/c/J, Rost 4/5/6, Leinen O/B/b/N, Stein g/s/S, Haut h/2 und
  // 'G' = Krapp-Altrosa (Leitfarbe Hedda, Akzent Corm).
  // ==========================================================================
  // BRAN DER SCHMIED — Lederschurz J/c mit Rostnieten, blosse Arme, grauer Bart.
  npc_bran_0: [
    '.......__hk.....',
    'TLDT._hhhhhk....',
    'TLDD_hhhhhhh2k..',
    'TLTk_hnnnnn22k..',
    'kTTk2h22222h2k..',
    '...j2hkhhk2h2k..',
    '...j2hh22hhh2k..',
    '...jsFFFFFFssk..',
    '...jsFFFFFFssk..',
    '._;jsFFFFFss;k..',
    '._;jssSSSSS;;;k.',
    '.2hj;QSSS;Q;hh2k',
    '.2hj;Q;S;;Q;hh2k',
    '.2hh;Q;;;;Q;hh2k',
    '.._QQQLQQQQQhh2k',
    '.._:;?;;;:::hh2k',
    '.._:;?;;::::hh2k',
    '..?:;;;;;;;::hhk',
    '..??;?;;;::::k..',
    '..??;?;;;::::k..',
    '..?;?::;:::::k..',
    '..?;?::;:::::k..',
    '..jjjjk.jjjjk...',
    '..jqqqk.jqqqk...',
  ],
  npc_bran_1: [
    '.......__hk.....',
    '.LDT._hhhhhk....',
    'TLDD_hhhhhhh2k..',
    'TLTk_hnnnnn22k..',
    'kTTTkhh2222h2k..',
    '...j2hkhhk2h2k..',
    '...j2hh22hh22k..',
    '...jsFFFFFFFssk.',
    '._;jsFFFFFFssk..',
    '._;j:sFFFFss;;k.',
    '.2hj:sSSSsss;;k.',
    '.2hj;QSSSsQ;hh2k',
    '.2hh;Q;SS;Q;hh2k',
    '..2h;Q;;;;Q;hh2k',
    '._QQQLQQQQQQhh2k',
    '.;::;;;;;;;:hh2k',
    '._::;;;;;:::hh2k',
    '.?::;;;;;;;::hhk',
    '.?;;;;;;;;:::k..',
    '.?;;;;;;;;:::k..',
    '.?;?::;;:::::k..',
    '.?;?::;;:::::k..',
    '.jjjjk...jjjjk..',
    '.jqqqk...jqqqk..',
  ],
  // ALTE HEDDA — Krapp-Umhang 'G' (LEITFARBE der Umwidmung), r-Falten, Stock.
  npc_hedda_0: [
    '.....__k........',
    '...._???Bk......',
    '..._????BBk.....',
    '...O???BBBk.....',
    '...O?nnnnnBk....',
    '...O?22222Bk....',
    '...O?hkhk2Bk....',
    '..BO?2h222BOk...',
    '._BOB2hh22BOOk..',
    '._BB22222BOOOOk.',
    '._BBBBBBBOOOO!k.',
    '._BBBBBBOOOJ!!k.',
    '.hhh%BBOOhJG!k..',
    '..%%%%%%GGJG!k..',
    '..%%%%%%%J!!k...',
    '..%%%%%%QG!k....',
    '..%%%%%%QG!k....',
    '...%%%%%QG!k....',
    '...%%%%Q%%!k....',
    '...%%%Q%%%!k....',
    '....%j%%%!k.....',
    '....j%%%%!k.....',
    '...j%%%%G!k.....',
    '..Qjjjk.jjk.....',
  ],
  npc_hedda_1: [
    '.....__k........',
    '...._???Bk......',
    '..._????BBk.....',
    '...O???BBBk.....',
    '...O?nnnnnBk....',
    '...O?22222Bk....',
    '...O?hkhk2Bk....',
    '.._B?2h222BOOk..',
    '._BOB2hh22BOOOk.',
    '_BBB22222BOOOOOk',
    '._BBBBBBBOOOO!k.',
    '.!BBBBBBOOOJ!!k.',
    '..hh%BBOOhJG!k..',
    '..%%%%%%GGJG!k..',
    '..%%%%%%QGGk....',
    '..%%%%%%QGGGk...',
    '..%%%%%%QG!k....',
    '...%%%%GQG!k....',
    '...%%%%Q%%!k....',
    '...%%%Q%%%!k....',
    '...%%j%%G!k.....',
    '...j%%%%%!k.....',
    '..%j%%%GG!kk....',
    '..Qjjjk.jjk.....',
  ],
  // VATER CORM — dunkle Kutte n/g/s, Krapp-Stola als einziger Akzent, Buch.
  npc_corm_0: [
    '.......)(.......',
    '......|((k......',
    '.....|((((k.....',
    '....)((((((k....',
    '....)(((((((k...',
    '....)(nnnnn(k...',
    '....)(22h22(k...',
    '....)(hkhk2(k...',
    '....)(hh222(k...',
    '....)&bbBBBk....',
    '...)((bbbBB&k...',
    '...)((GGGG&&&k..',
    '...)((G&hQJJJJQk',
    '...&)(G&hQbbbbQk',
    '...&)(G&&QJJJJQk',
    '..&)(GG((&&&&k..',
    '..&)(GG((&&&&k..',
    '..&)(GG((&&&&k..',
    '..&)(G((((&&&k..',
    '..&)((((((&&&k..',
    '..&)((((((&&k...',
    '..&)(((((&&&&k..',
    '..&)(((((&&&&k..',
    '..&&(((nn&&&&k..',
  ],
  npc_corm_1: [
    '.......)(.......',
    '......|((k......',
    '.....|(((k......',
    '....)((((((k....',
    '....)(((((((k...',
    '....)(nnnnn(k...',
    '....)(22h22(k...',
    '....)(hkhk2(k...',
    '....)(hh222((k..',
    '...)((bbBBB(k...',
    '...)((bbbB(&&k..',
    '...)((GGGG(&&k..',
    '...)((G&hQJJJJQk',
    '...&)(G&hQbbbbQk',
    '...&)(G&&QJJJJQk',
    '..&))(GG((&&k...',
    '..&))(GG((&&k...',
    '..&))(G((((&k...',
    '..&))((((((&k...',
    '..&)((((((&&k...',
    '..&)((((((&&&k..',
    '..&)(((((&&&&k..',
    '..&)(((((&&&&k..',
    '..&&(((n&&&&&k..',
  ],
  // MILE, DAS BOTENKIND — kleiner Wuchs (Kopf ab Zeile 4), Leinenkittel, Tasche.
  npc_mile_0: [
    '................',
    '................',
    '................',
    '.....jj__jjk....',
    '.....jjccjjk....',
    '.....jccccjjk...',
    '.....jcccjjjk...',
    '.....jhkhkh2k...',
    '.....jhhhhh2k...',
    '.....2h22hh2k...',
    '.....2hhhh2k....',
    '......hhhh2k....',
    '......]]][[k....',
    '.....]]]]JJ[k...',
    '..qJJ]]]JJ[[k...',
    '..qJhh]JJ[[@k...',
    '..qJQ[JJ[[[@hk..',
    '..kkk[[[[[[@hk..',
    '....][[[[[@k....',
    '....][[[[[@k....',
    '....][[[[[@k....',
    '.....2h2.2hk....',
    '.....2h2.2hhk...',
    '....JJqk.JJqk...',
  ],
  npc_mile_1: [
    '................',
    '................',
    '................',
    '......jj__jjk...',
    '......jjccjjk...',
    '......jccccjjk..',
    '......jcccjjjk..',
    '......jhkhkh2k..',
    '.....2hhhhh2k...',
    '.....2h22hh2k...',
    '.....2hhhh2k....',
    '......hhhh2k....',
    '......]]][[k....',
    '.....]]]]JJ[hk..',
    '..qJJ]]]JJ[[hk..',
    '..qJhh]JJ[[@2k..',
    '.qJQQ[JJ[[[@hk..',
    '.kkkk[[[[[[@k...',
    '....][[[[[@k....',
    '....][[[[[@k....',
    '....][[[[[@k....',
    '.....2h2.2hk....',
    '.....2h2.2hhk...',
    '.....JJqkJJqk...',
  ],
  // DER TORWAECHTER — Eisenhaube g/s/S, Rostpanzer 4/5/6, Speer rechts.
  // SCHLUESSEL-PAARUNG (Fixer R1, V-SPEC BLOCKER): npcs.js:185-187 bildet den
  // Sprite-Schluessel als `npc_${n.id}_<frame>`, und die id des fuenften NPC
  // heisst in map_dorf.js/npc_dialoge.js/quest.js 'torwaechter'. Der frueher
  // hier stehende Kurzname 'npc_wache_*' lief in allen drei drawNpc-Fallbacks
  // ins Leere — der Torwaechter wurde NICHT gezeichnet.
  npc_torwaechter_0: [
    '...............I',
    '..............iI',
    '....||Iik.....ii',
    '...|iiiiCk....ci',
    '...CiiiiCCk...Jc',
    '...CnnnnCk....Jc',
    '...Chkhk2k....Jc',
    '...Chhh22k....Jc',
    '...Chnnh2k....Jc',
    '...C2hh2Ck....Jc',
    '||6666666554kJc.',
    '|66666665554kJc.',
    '.|556656654k.Jc.',
    '.|556656654k.Jc.',
    '.6556656542hhhc.',
    '.6554444454k.Jc.',
    '.6556656554k.Jc.',
    '..656656554kJc..',
    '..kqqjjqqjk.Jc..',
    '.||55665564kJc..',
    '..66544566k.Jc..',
    '..6654665k.Jc...',
    '..6654665k.Jc...',
    '.jjqqkjjqqkJc...',
  ],
  npc_torwaechter_1: [
    '...............I',
    '..............iI',
    '....||Iik.....ii',
    '...|iiiiCk....ci',
    '...CiiiiCCk...Jc',
    '...CnnnnCk....Jc',
    '...C2hkhkk....Jc',
    '...C2hhh2k....Jc',
    '...Chnnh2k....Jc',
    '...C2hh2Ck....Jc',
    '.|6666666554kJc.',
    '|66666665554kJc.',
    '.|556656654k.Jc.',
    '.|556656654k.Jc.',
    '.6556656542hhhc.',
    '.6554444454k.Jc.',
    '.6556656554k.Jc.',
    '..656656554kJc..',
    '.kqqjjqqjk..Jc..',
    '||55665564k.Jc..',
    '.66544566k..Jc..',
    '.6654665k...Jc..',
    '.6654665k...Jc..',
    'jjqqkjjqqk..J...',
  ],
  // Hinweisblase ueber Quest-Gebern (8x8).
  // SLICE 6 PHASE 4a: die Platte war mit N (L233) nach der Flamme das Hellste
  // im Bild. Jetzt warmes Pergament B (L139) mit Innenfeld O (L102); die
  // Glyphe bleibt r (L52), Kontrast 87 L.
  // SCHLUESSEL-PAARUNG (Fixer R1, V-SPEC MAJOR): npcs.js:218 liest gfx.npc_blase.
  // Unter dem frueheren Namen 'npc_bubble' war die '!'-Blase ein stiller No-op.
  npc_blase: [
    '.kkkkkk.',
    'kBBBBBBk',
    'kBOrrOBk',
    'kBOrrOBk',
    'kBOrrOBk',
    'kBBOOBBk',
    'kBOrrOBk',
    '.kkkkkk.',
  ],

  // ==========================================================================
  // SPRECH-FRAMES (Fixer R1, V-SPEC MAJOR "Sprech-Frames fehlen vollstaendig").
  // SPEC Rev 1 §2.1/§2.2 nennt neben dem 2-Frame-Idle ausdruecklich einen
  // Sprech-Frame; npcs.js:185 fragt ihn als `npc_<id>_talk` ab und fiel bisher
  // still auf den Idle-Frame zurueck.
  // BAUART: Grundlage ist IMMER Frame _0 (gleiche Fusslinie, gleicher Rumpf —
  // im Dialog steht der NPC still), veraendert ist AUSSCHLIESSLICH die
  // Mundzeile: aus der geschlossenen Lippe '22' wird die offene Mundhoehle
  // '2kk2' (k = Umriss/Schatten, 2 = dunkler Hautton als Lippenrand). Ein
  // groesserer Ausschlag flackert bei 8x8-Kopfgroesse.
  // APPEND-ONLY ANS LISTENENDE (§0.6): die Indizes 0..74 des Bestands und die
  // Reihenfolge der zehn Idle-Grids bleiben unberuehrt.
  // ==========================================================================
  npc_bran_talk: [
    '.......__hk.....',
    'TLDT._hhhhhk....',
    'TLDD._hhhhhhh2k.',
    'TLTk._hnnnnn2Sk.',
    'kTTk.2h22222h2k.',
    '...j.2hkhhk2h2k.',
    '...j.2h2kkhhh2k.',
    '...jsFF22FFFssk.',
    '...jsFFFFFFssk..',
    '._;jsFFFFFss;h2k',
    '._;jssSSSsss;h2k',
    '.2hj;QSSS;Q;hh2k',
    '.2hj;Q;S;;Q;;h2k',
    '.2hh;Q;;;;Q;;;2k',
    '.._QQQLQQQQQ;;;k',
    '.._:;?;;;:::;;;k',
    '.._:;?;;:::::::k',
    '..??;?;;;;;::::k',
    '..??;?;;;::::k..',
    '..??;?;;;::::k..',
    '..?;?::;:::::k..',
    '..?;?::;:::::k..',
    '..jjjjk.jjjjk...',
    '..jqqqk.jqqqk...',
  ],
  npc_hedda_talk: [
    '.....__k........',
    '...._????k......',
    '...._????BBk....',
    '....O???BBk.....',
    '....O?nnnnnBk...',
    '....O?22222Bk...',
    '....O?hkhk2Bk...',
    '...BO?2kk22Bk...',
    '._BOB22hh22BOk..',
    'h_BB22222BOOOOk.',
    'h2BBBBBBBOOO!!k.',
    '2hhBBBBBOOOJ!!k.',
    '.hhh%BBOOhJG!k..',
    '..%%%%%%GGJG!k..',
    '..%%%%%%%J!!k...',
    '..%%%%%%QG!k....',
    '..%%%%%%QG!k....',
    '...%%%%%QG!k....',
    '...%%%%Q%%!k....',
    '...%%%Q%%%!k....',
    '....%j%%%!k.....',
    '....j%%%%!k.....',
    '...j%%%%G!k.....',
    '..Qjjjk.jjk.....',
  ],
  npc_corm_talk: [
    '.......)(.......',
    '......|((k......',
    '.....|((((k.....',
    '....)((((((k....',
    '....)(((((((k...',
    '....)(nnnnn(k...',
    '....)(22h22(k...',
    '....)(hkhk2(k...',
    '....)(h2kk2(k...',
    '....)&bb222k....',
    '...)((bbb(&(hQJQ',
    '...)((GGG(&hQbbQ',
    '...)((G&&&&hQJJQ',
    '...&)(G&&&&&&k..',
    '...&)(G&&&&&k...',
    '..&)(GG((&&&&k..',
    '..&)(GG((&&&k...',
    '..&)(G((((&&&k..',
    '..&)((((((&&&k..',
    '..&)((((((&&&k..',
    '..&)(((((&&&&k..',
    '..&)(((((&&&&k..',
    '..&)(((((&&&&k..',
    '..&&(((nn&&&&k..',
  ],
  npc_mile_talk: [
    '................',
    '................',
    '.....jj__jjk....',
    '.....jjccjjk....',
    '.....jccccjjk...',
    '.....jcccjjjk...',
    '.....jhkhkh2k...',
    '.....jhh2h22k...',
    '.....2hkkhh2k...',
    '.....2hnnh22k...',
    '.....2hhhhh2k...',
    '......2hhh2k....',
    '.....]]]][[k....',
    '....]]]]]JJ[hk..',
    '..qJJ]]]JJ[[hk..',
    '..qJhh]JJ[[@2k..',
    '..qJQ[JJ[[[@k...',
    '..kkk[[[[[[@k...',
    '....][[[[[@k....',
    '....][[[[[@k....',
    '....][[[[[@k....',
    '.....2h2.2hk....',
    '.....2h2.2hhk...',
    '....JJqk.JJqk...',
  ],
  npc_torwaechter_talk: [
    '...............I',
    '..............iI',
    '....||Iik.....ii',
    '...|iiiiCk....ci',
    '...CiiiiCCk...Jc',
    '...CnnnnCk....Jc',
    '...Ckhkh2k....Jc',
    '.hhChhhh2k....Jc',
    '.2hCkkkh2k....Jc',
    '.2hChhhh2k....Jc',
    '||6666666554kJc.',
    '|66666665554kJc.',
    '.|556656654k.Jc.',
    '.|556656654k.Jc.',
    '.6556656542hhhc.',
    '.6554444454k.Jc.',
    '.6556656554k.Jc.',
    '..656656554k.Jc.',
    '..kqqjjqqjk..Jc.',
    '.||55665564k.Jc.',
    '..66544566k..Jc.',
    '..6654665k..Jc..',
    '..6654665k..Jc..',
    '.jjqqkjjqqk.J...',
  ],

  // =========================================================================
  // GP7-CH-2 §4/V7/E-A4 — BODEN-DECALS (Stufe 2 des zweistufigen Sterbens).
  // EIGENE KEYS, ANS ENDE (§0.2: die Bestandsreihenfolge ist eingefroren;
  // Object.keys ist in allen Rigs live gelesen -> anhaengen ist folgenlos).
  // KEINE *_decal_flip-Keys: eine Leiche traegt keine Blickrichtung (E-A4);
  // damit bleiben die 37er-Flip-Liste main.js:106-128 und smoke:6396-6408
  // unangetastet. KEIN warden_decal (§8).
  //
  // PROVISORISCHER STAND (Engine-Agent, Phase 1e Schritt 1c): das jeweilige
  // *_die-Grid auf die untersten N BELEGTEN Zeilen beschnitten, N = min(6,
  // floor(0,4 * Basisgrid-Hoehe)), Hund hart 4 (E-B9); Breite = Basisgrid HEUTE
  // (rust 16 — Zeichner B stellt mit dem Rost-Commit auf 20 um und MUSS
  // rust_decal mit umstellen, sonst reisst das Decalmasse-Gate "Breite =
  // Basisgrid"). Die KUNST ersetzen die Zeichner unter dem Mutex: E-A4 fordert
  // einen messbaren Unterschied zu *_die (Texel-Diff >= 30 % ODER >= 2 Zeilen
  // flacher ODER Wertabsenkung >= 20 L), §1 <= 25 % Rahmenfuellung, und das
  // Hund-Decal ist eine NEUZEICHNUNG (R-A4, Band 8-11).
  // =========================================================================
  // NACHTRAG 12.09. (Fable): Zeichner B hat rust_0/_1/_die UND rust_decal in einem
  // Schreibvorgang auf 20x18 gestellt; die Breitenangabe 16 oben ist Historie.
  skeleton_decal: [
    '................',
    '................',
    '................',
    '.._///..........',
    './/k/...........',
    '.kkkk.//$$///$$.',
  ],
  // Stufe 2 (Decal), FIX 1 nach der neuen Decal-Regel: flacher Lumpenfleck,
  // nur die untersten zwei Zeilen belegt, BODENKANTE aus 'k' (4 Texel), Rim
  // nur 2 Texel oben (9,1 %), 22 Texel = 22,9 % Rahmenfuellung.
  ghoul_decal: [
    '................',
    '................',
    '................',
    '................',
    '...>>||<<HHdd...',
    '.dd<<kkkk<<dd...',
  ],
  hound_decal: [
    '................',
    '....|}}.........',
    '...}}}}}}``.....',
    '....{{..{{......',
  ],
  // Stufe 2 (Decal), FIX 1 nach der neuen Decal-Regel: flacher Rostschutt, nur
  // die untersten zwei Zeilen belegt, BODENKANTE aus 'k' (4 Texel), KEIN Rim
  // und kein '6' (eine Leiche glaenzt nicht), 28 Texel = 23,3 % Rahmenfuellung.
  // Breite = Basisgrid (20), unterste Zeile = Fuss.
  rust_decal: [
    '....................',
    '....................',
    '....................',
    '....................',
    '.........5544554444.',
    '445544554444kkkk44..',
  ],
};
