// FIGUREN-Grids (SPRITES). GP7-CH-1 P0.a (Spec E10, Landkarte V2): mechanisch
// aus art/sprites.js herausgeloest, Inhalt und Schluessel-Reihenfolge byte-gleich.
// art/sprites.js bleibt als Fassade bestehen und re-exportiert SPRITES unveraendert,
// jeder bestehende Import bleibt gueltig.
// REINES DATEN-MODUL: keine Ausfuehrungslogik, keine Zufalls- oder Zeitquellen,
// keine Audio-/Loop-Aufrufe (Quelltext-Waechter smoke_test.mjs:1780-1791 und
// :5257-5273 sind damit erfuellt).
//
// Pixel-Grids: jedes Zeichen = PALETTE-Key, '.' = transparent.
// Maße: player_* 16x24 (SoM-Proportion, Kopf ~1/3), ghoul_* 16x20,
// übrige Figuren 16x16, HUD-Herzen 8x8, potion 10x10, fog_blob 32x16.
// Slice 2: hound_* 16x12 (Seitenansicht, Blick nach rechts), rust_* 16x18,
// Boden-Drops und boomerang_* 10x10, sparkle_*/block_spark 8x8,
// icon_weapon/armor/ring 12x12, icon_boomerang 16x16, Schild-Overlays klein.
// Laufzyklus des Helden: 4 Frames pro Richtung, Beinstellungen
// _0 = Kontakt (linkes Bein vor), _1 = Passing, _2 = Kontakt gespiegelt, _3 = Passing.
// Kontakt-Frames haben Fußsohle auf Zeile 23, Passing-Frames enden auf Zeile 22
// (Körper-Bob über den Zeichen-Anker). Sekundärbewegung: der Umhangsaum liegt
// in den Passing-Frames (_1/_3) anders als in den Kontakt-Frames (_0/_2).
//
// HELD-TONLEITER (GP7-CH-1 Phase 1a, Licht von oben LINKS):
//   _  Rimlicht warm, IMMER 1 px, nur obere Lichtkante (Kapuzenkuppel,
//      Schulterecke). ART_DIRECTION Regel 10 erlaubt warm ODER kalt nach
//      Lichtsituation der Figur — das Dorf ist fackelbeleuchtet, also warm.
//   Z  Stoff-Spitzlicht / weiche Lichtkante der linken (Licht-)Silhouette
//   ^  Stoff-Zwischenstufe (schließt die X->Z-Schlucht, Schrittverhältnis 1,50)
//   X  beleuchteter Stoff   U  Stoffmasse (Leitton)   u  Stoffschatten und
//   zugleich Umriss der LICHTSEITE (Stilregel 2: dunkelster Materialton statt k)
//   k  Umriss der SCHATTENSEITE (rechts/unten)   n  Tiefschatten
//      (Kapuzeninnenraum über dem Gesicht, Gürtellinie)
// Gesichtsfeld 5x5 in der Kapuze: n-Brauenschatten, 2 einzelne k-Augentexel,
// h-Wangenlicht links, 2-Schatten rechts. Kapuzenspitze außermittig LINKS,
// Schwertgriff bricht die Silhouette rechts oben, Saum schwingt rechts aus.

export const SPRITES = {
  // Held: Kapuzen-Wanderer, Schwertgriff über der rechten Schulter (Rückentrage)
  player_down_0: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX22222ukjYk.',
    '...uXhkhk2ukYyYk',
    '...uXhh222ukik..',
    '...uuu222uuuk...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnjjnnUuk..',
    '.ZhUuUUUUUUhuk..',
    '.uuUUXXUUUUhuuk.',
    '.uuUXXUUUUUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '..uUUUk..uUUUkk.',
    '..uUUUk..uUUUk..',
    '..uUUUk..qjqqk..',
    '..qjqqk..qjqqk..',
    '..qjqqk..qjjjk..',
    '..qjjjk..kkkkk..',
    '..kkkkk..nnnn...',
  ],
  player_down_1: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX22222ukjYk.',
    '...uXhkhk2ukYyYk',
    '...uXhh222ukik..',
    '...uuu222uuuk...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnjjnnUuk..',
    '.ZhUuUUUUUUhuk..',
    '.uuUUXXUUUUhuuk.',
    '..uUXXUUUUUUZZuk',
    '..knuuUUUUUuUZuk',
    '...uUUUk.uUUUk.k',
    '...uUUUk.uUUUk..',
    '...qjqqk.qjqqk..',
    '...qjqqk.qjqqk..',
    '...qjjjk.qjjjk..',
    '...kkkkk.kkkkk..',
    '....nnnnnnnnn...',
  ],
  player_down_2: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX22222ukjYk.',
    '...uXhkhk2ukYyYk',
    '...uXhh222ukik..',
    '...uuu222uuuk...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnjjnnUuk..',
    '.ZhUuUUUUUUhuk..',
    '.uuUUXXUUUUhuuk.',
    '.uuUXXUUUUUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '...uUUUk..uUUUk.',
    '...qjqqk..uUUUk.',
    '...qjqqk..uUUUk.',
    '...qjqqk..qjqqk.',
    '...qjjjk..qjqqk.',
    '...kkkkk..qjjjk.',
    '....nnnn..kkkkk.',
  ],
  player_down_3: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX22222ukjYk.',
    '...uXhkhk2ukYyYk',
    '...uXhh222ukik..',
    '...uuu222uuuk...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnjjnnUuk..',
    '.ZhUuUUUUUUhuk..',
    '.uuUUXXUUUUhUUuk',
    '..uUXXUUUUUUUZuk',
    '..knuuUUUUUuUZZk',
    '...uUUUk.uUUUk.k',
    '...uUUUk.uUUUk..',
    '...uUUUk.uUUUk..',
    '...qjqqk.qjqqk..',
    '...qjqqk.qjqqk..',
    '...qjjjk.qjjjk..',
    '....kkkkkkkkk...',
  ],
  // Rückansicht: Schwert komplett auf dem Rücken sichtbar
  player_up_0: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXUUuUUuk.yk.',
    '...uXUUuUUukjYk.',
    '...uXUUuUUukYyYk',
    '...uXUUuUUukiC..',
    '...uuuUuUUUkiC..',
    '.ZZ^^^nuUUUiCk..',
    '.Z^UuUnuUUUiCk..',
    '.Z^UuUXXXUiCUuk.',
    '.ZhUunnjjniCUuk.',
    '.ZhUuUUUUiCUhuk.',
    '.uuUUXXUUiCUUuk.',
    '.uuUXXUUUCUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '..uUUUk..uUUUkk.',
    '..uUUUk..uUUUk..',
    '..uUUUk..qjqqk..',
    '..qjqqk..qjqqk..',
    '..qjqqk..qjjjk..',
    '..qjjjk..kkkkk..',
    '..kkkkk..nnnn...',
  ],
  player_up_1: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXUUuUUuk.yk.',
    '...uXUUuUUukjYk.',
    '...uXUUuUUukYyYk',
    '...uXUUuUUukiC..',
    '...uuuUuUUUkiC..',
    '.ZZ^^^nuUUUiCk..',
    '.Z^UuUnuUUUiCk..',
    '.Z^UuUXXXUiCUuk.',
    '.ZhUunnjjniCUuk.',
    '.ZhUuUUUUiCUhuk.',
    '.uuUUXXUUiCUUuk.',
    '..uUXXUUUCUUZZuk',
    '..knuuUUUUuUZuk.',
    '...uUUUk.uUUUk.k',
    '...uUUUk.uUUUk..',
    '...qjqqk.qjqqk..',
    '...qjqqk.qjqqk..',
    '...qjjjk.qjjjk..',
    '...kkkkk.kkkkk..',
    '....nnnnnnnnn...',
  ],
  player_up_2: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXUUuUUuk.yk.',
    '...uXUUuUUukjYk.',
    '...uXUUuUUukYyYk',
    '...uXUUuUUukiC..',
    '...uuuUuUUUkiC..',
    '.ZZ^^^nuUUUiCk..',
    '.Z^UuUnuUUUiCk..',
    '.Z^UuUXXXUiCUuk.',
    '.ZhUunnjjniCUuk.',
    '.ZhUuUUUUiCUhuk.',
    '.uuUUXXUUiCUUuk.',
    '.uuUXXUUUCUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '...uUUUk..uUUUk.',
    '...qjqqk..uUUUk.',
    '...qjqqk..uUUUk.',
    '...qjqqk..qjqqk.',
    '...qjjjk..qjqqk.',
    '...kkkkk..qjjjk.',
    '....nnnn..kkkkk.',
  ],
  player_up_3: [
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXUUuUUuk.yk.',
    '...uXUUuUUukjYk.',
    '...uXUUuUUukYyYk',
    '...uXUUuUUukiC..',
    '...uuuUuUUUkiC..',
    '.ZZ^^^nuUUUiCk..',
    '.Z^UuUnuUUUiCk..',
    '.Z^UuUXXXUiCUuk.',
    '.ZhUunnjjniCUuk.',
    '.ZhUuUUUUiCUhuk.',
    '.uuUUXXUUiCUUUuk',
    '..uUXXUUUCUUUZuk',
    '..knuuUUUUuUZZk.',
    '...uUUUk.uUUUk.k',
    '...uUUUk.uUUUk..',
    '...uUUUk.uUUUk..',
    '...qjqqk.qjqqk..',
    '...qjqqk.qjqqk..',
    '...qjjjk.qjjjk..',
    '....kkkkkkkkk...',
  ],
  // side = nach rechts; Schwert locker in der vorderen Hand
  player_side_0: [
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2khk..',
    '..uXUUUuun22hhk.',
    '..uXUUUuun22nk..',
    '..uuXUUuuuu2k...',
    '.uXUXXUUUUUuk...',
    '.uXUuUXXUUUuk...',
    '.uXUuUXXXUUuk...',
    '.uXUuUUUUUhYiiiI',
    '.uXUuUUUUUUhuk..',
    'uuXUUXXUUUU2uk..',
    'uuuUUUUUUUUUuk..',
    'knuuUUUUUUUuk...',
    '..uUUUk.uUUUk...',
    '.uUUUk...uUUUk..',
    '.qjqqk...qjqqk..',
    'qjqqk.....qjqqk.',
    'qjjjk.....qjqqk.',
    'kkkkk.....qjjjk.',
    'nnnn.......kkkkk',
  ],
  player_side_1: [
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2khk..',
    '..uXUUUuun22hhk.',
    '..uXUUUuun22nk..',
    '..uuXUUuuuu2k...',
    '.uXUXXUUUUUuk...',
    '.uXUuUXXUUUuk...',
    '.uXUuUXXXUUuk...',
    '.uXUuUUUUUhYiiiI',
    '.uXUuUUUUUUhuk..',
    'uuXUUXXUUUU2uk..',
    'uuuXUUUUUUUUUuk.',
    'knuuUUUUUUUUuk..',
    '...uUUUkuUUUk...',
    '...uUUUkuUUUk...',
    '...qjqqkqjqqk...',
    '...qjqqkqjqqk...',
    '...qjjjkqjjjk...',
    '...kkkkkkkkkk...',
    '....nnnnnnnn....',
  ],
  player_side_2: [
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2khk..',
    '..uXUUUuun22hhk.',
    '..uXUUUuun22nk..',
    '..uuXUUuuuu2k...',
    '.uXUXXUUUUUuk...',
    '.uXUuUXXUUUuk...',
    '.uXUuUXXXUUuk...',
    '.uXUuUUUUUhYiiiI',
    '.uXUuUUUUUUhuk..',
    'uuXUUXXUUUU2uk..',
    'uuuUUUUUUUUUuk..',
    'knuuUUUUUUUuk...',
    '..uUUUk.uUUUk...',
    '..uUUUk...uUUUk.',
    '..qjqqk...qjqqk.',
    '.qjqqk.....qjqqk',
    '.qjqqk.....qjjjk',
    '.qjjjk.....kkkkk',
    '.kkkkknn...nnnn.',
  ],
  player_side_3: [
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2khk..',
    '..uXUUUuun22hhk.',
    '..uXUUUuun22nk..',
    '..uuXUUuuuu2k...',
    '.uXUXXUUUUUuk...',
    '.uXUuUXXUUUuk...',
    '.uXUuUXXXUUuk...',
    '.uXUuUUUUUhYiiiI',
    '.uXUuUUUUUUhuk..',
    'uuXUUXXUUUUU2uk.',
    'uuuXUUUUUUUUUuk.',
    'knuuUUUUUUUUuk..',
    '...uUUUkuUUUk.uk',
    '...uUUUkuUUUk...',
    '...uUUUkqjqqk...',
    '...qjqqkqjqqk...',
    '...qjqqkqjjjk...',
    '...qjjjkkkkkk...',
    '...kkkkknnnn....',
  ],
  // Angriff: Ausfallschritt, Klinge stößt nach unten an der rechten Seite
  player_attack_down: [
    '................',
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk....',
    '...uX22222uk....',
    '...uXhkhk2uk....',
    '...uXhh222uuk...',
    '...uuu222uUUuk..',
    '.ZZ^^^^UUUUUUuk.',
    '.Z^UuUXXUUUUhYk.',
    '.Z^UuUXXXUUUuyYk',
    '.ZhUunnjjnnUukiI',
    '.ZhUuUUUUUUUukCi',
    '.uuUUXXUUUUUuk.i',
    '.uuUXXUUUUUUk..i',
    '.knuuUUUUUuk...i',
    '.uUUUk..uUUUk..C',
    '.uUUUk..uUUUk...',
    '.qjqqk..uUUUk...',
    '.qjjjk..qjqqk...',
    '.kkkkk..qjqqk...',
    '..nnn...qjjjkn..',
  ],
  // Angriff nach oben: Klinge über dem Kopf, Ausfallschritt nach hinten
  player_attack_up: [
    '..............I.',
    '..............i.',
    '.....__.......i.',
    '....ZZXuk.....i.',
    '...Z^^XUUuk...i.',
    '...ZXXUUUXuk..i.',
    '...uXUUuUUukjYy.',
    '...uXUUuUUukyYk.',
    '...uXUUuUUuhkk..',
    '...uuuUuUUU2k...',
    '.ZZ^^^^UUUUUuk..',
    '.Z^UuUXXUUUUuk..',
    '.Z^UuUXXXUUUuk..',
    '.ZhUunnnnnUUuk..',
    '.ZhUuUUUUUUUuk..',
    '.uuUUXXUUUUUUuk.',
    '.uuUXXUUUUUUZuk.',
    '.kkuuUUUUuuUZuk.',
    '..qjqqk..uUUUk..',
    '..qjqqk..uUUUk..',
    '..qjjjk..qjqqk..',
    '..kkkkk..qjqqk..',
    '...nnn...qjjjk..',
    '.........kkkkkn.',
  ],
  // Angriff seitlich: tiefer Ausfallschritt, gestreckter Arm, lange Klinge
  player_attack_side: [
    '................',
    '................',
    '....__..........',
    '...ZZZuk........',
    '..uX^^UUUuk.....',
    '..uXXUUUUUUuk...',
    '..uXUUUuunnnk...',
    '..uXUUUuun2knk..',
    '..uXUUUuun2hhhk.',
    '..uuXUUuun22k...',
    '.uXUXXUUUuu2uk..',
    '.uXUuUXXUUUUuk..',
    '.uXUuUXXXUUUhYiI',
    'uuXUuUUUUUUUuykk',
    'uuXUuUUUUUUUhuk.',
    'uuuXUUXXUUUU2uk.',
    'uuuXUUUUUUUuk...',
    'knuuUUUUUUuk....',
    '..uUUUk.uUUUk...',
    '.uUUUk....uUUUk.',
    '.qjqqk.....uUUUk',
    'qjqqk......qjqqk',
    'qjjjk......qjqqk',
    'kkkkknn....qjjjk',
  ],
  // Held stirbt: sackt in die Knie (Augen zu), dann liegend im Umhang
  player_die_0: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....__.........',
    '....ZZXuk.......',
    '...Z^^XUUuk.....',
    '...Z^^UUUUuk....',
    '...uXnnnnnuk.yk.',
    '...uX2kk22ukjYk.',
    '...uuu2222ukYyYk',
    '.ZZ^^^^UUUUUuik.',
    '.Z^UuUXXUUUUukC.',
    '.Z^UuUXXXUUUuk..',
    '.ZhUuUUUUUUUuk..',
    '.ZhUuUUUUUUUuk..',
    '.uuUUXXUUUUUUuk.',
    '.uuUXXUUUUUUZuk.',
    'ZuknuuUUUUUuUZk.',
    '.uuknuUUUUUuZZk.',
    '..kkkUUUkkUUUkk.',
    '...nnnnnnnnnnn..',
  ],
  player_die_1: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...........YiiiI',
    '..........yk....',
    '....__.....k....',
    '..Z^^XXuk.......',
    '.ZXXXUUUUuuk....',
    '.ZXU2kk2UUUUuk..',
    '.uXU22222UUUUuk.',
    '.uuXUUUUUUUUUZuk',
    '..uknuuUUUuuUZuk',
    '...kkkkkkkkkkkk.',
  ],
  // Skelett (GFX3 §3.4): FRONTAL neu — klarer Schädel mit 2 Augenhöhlen, Nasal-
  // höhle, 2px-Knochen, Arme unten-außen, durchgehender k-Umriss, b-dominant,
  // N nur 1px-Rim. Liest sofort als Skelett (nie Spinne). GP2-Kontaktschatten
  // ENTFERNT (§2.5-Weichschatten der Engine übernimmt) — keine Fuß-Schattenzeile.
  skeleton_0: [
    '................',
    '....kkkkkkkk....',
    '...kNbbbbbbNk...',
    '...kbNNbbbbbk...',
    '...kbkkbbkkbk...',
    '...kBbbkkbbBk...',
    '....kBbbbbBk....',
    '..NbkbbBbbbkbb..',
    '.bBb.bBkkBb.bBb.',
    '.bBb.bkbbkb.bBb.',
    '.bBb.kbBBbk.bBb.',
    '..bb..kbbk..bb..',
    '......kbbk......',
    '.....kbk.kbk....',
    '.....kbk.kbk....',
    '....kkk...kkk...',
  ],
  skeleton_1: [
    '................',
    '....kkkkkkkk....',
    '...kNbbbbbbNk...',
    '...kbNNbbbbbk...',
    '...kbkkbbkkbk...',
    '...kBbbkkbbBk...',
    '....kBbbbbBk....',
    '..NbkbbBbbbkbb..',
    '.bBb.bBkkBb.bBb.',
    '.bBb.bkbbkb.bBb.',
    '.bBb.kbBBbk.bBb.',
    '..bb..kbbk..bb..',
    '......kbbk......',
    '.....kbk.kbk....',
    '....kbk...kbk...',
    '...kkk.....kkk..',
  ],
  skeleton_die: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '......kbbbbk....',
    '.....kbNbbNbk...',
    '...kbkbkkbkbbk..',
    '..kbBbkbbkbBbbk.',
    '..kkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  // Ghul 16x20: aufgedunsener Untoter, hängende Arme, breiter Rumpf
  // GFX4 (§3.4a): Neuzeichnung mit WERTSPRUNG. Heller Schaedel ('3'/'H' am Kopf
  // konzentriert, Zeilen 1-6) vs. dunkleres Koerper-Tuch ('G'/'d' abgedunkelt,
  // Zeilen 7-19). Kuehler Rim 'C' bleibt an der lichtabgewandten linken Kante.
  // Masse fix 16x20.
  ghoul_0: [
    '....kkkkkk......',
    '...k3HHHH3kk....',
    '..kC3HHHHHH3k...',
    '..kC3HkkkHH3k...',
    '..kC3HHdHHH3k...',
    '...kC3HddHH3k...',
    '...kkC3HH3kkk...',
    '..kdddddddddk...',
    '.kCdddddddgggk..',
    '.kCdddgddgggggk.',
    'kdkCddgddggggkdk',
    'kdkCddggdgggkkdk',
    'kgk.ddggggk.kgk.',
    'kkk.kdggdk..kkk.',
    '....kdggdk......',
    '....kgddgk......',
    '....kgk.kgk.....',
    '....kgk.kgk.....',
    '...kggk.kggk....',
    '...kkkk.kkkk....',
  ],
  ghoul_1: [
    '....kkkkkk......',
    '...k3HHHH3kk....',
    '..kC3HHHHHH3k...',
    '..kC3HkkkHH3k...',
    '..kC3HHdHHH3k...',
    '...kC3HddHH3k...',
    '...kkC3HH3kkk...',
    '..kdddddddddk...',
    '.kCdddddddgggk..',
    '.kCdddgddgggggk.',
    'kdkCddgddggggkdk',
    'kdkCddggdgggkkdk',
    'kgk.ddggggk.kgk.',
    'kkk.kdggdk..kkk.',
    '....kdggdk......',
    '....kggdgk......',
    '....kgk..kgk....',
    '...kgk...kgk....',
    '..kggk...kggk...',
    '..kkkk...kkkk...',
  ],
  ghoul_die: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...kk3H3kkk.....',
    '..kC3HggHd3kk...',
    '..kddggddggdk...',
    '..kgdggggdggk...',
    '..kkkkkkkkkkk...',
  ],
  // Schwert-Schwünge: Stahlbogen mit hellem Blitz
  sword_slash_down: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.C..............',
    'CiC............C',
    '.iiC..........CC',
    '..iiC........Cii',
    '...iiCC....CCii.',
    '....IiiCCCCiii..',
    '.....IIiiiiiI...',
    '......IIIIII....',
    '................',
  ],
  sword_slash_up: [
    '................',
    '......IIIIII....',
    '.....IIiiiiiI...',
    '....IiiCCCCiii..',
    '...iiCC....CCii.',
    '..iiC........Cii',
    '.iiC..........CC',
    'CiC............C',
    '.C..............',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  sword_slash_side: [
    '................',
    '.......C........',
    '......CiC.......',
    '.......iiC......',
    '........iiC.....',
    '.........IiC....',
    '.........IiiC...',
    '..........IiC...',
    '..........IiC...',
    '.........IiiC...',
    '.........IiC....',
    '........iiC.....',
    '.......iiC......',
    '......CiC.......',
    '.......C........',
    '................',
  ],
  coin_0: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '......kkkk......',
    '.....kyyyYk.....',
    '....kybyyYYk....',
    '....kybyyYYk....',
    '....kyyyyYYk....',
    '.....kyYYYk.....',
    '......kkkk......',
    '................',
    '................',
    '................',
    '................',
  ],
  coin_1: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......kk.......',
    '......kyYk......',
    '......kbYk......',
    '......kyYk......',
    '......kyYk......',
    '......kyYk......',
    '.......kk.......',
    '................',
    '................',
    '................',
    '................',
  ],
  // Zerschlagbare Props: Ton-Vase und Stein-Urne (AABB 12x12)
  vase: [
    '................',
    '................',
    '......kkk.......',
    '.....kJQqk......',
    '......kQk.......',
    '.....kJQqk......',
    '....kJJQQqk.....',
    '...kJJQQQjqk....',
    '...kJQQQQjqk....',
    '...kQQQQQjqk....',
    '...kQQQjjqqk....',
    '....kQQjjqk.....',
    '.....kjqqk......',
    '.....kkkkk......',
    '................',
    '................',
  ],
  urn: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kDDLLTTk....',
    '.....kkkkkk.....',
    '.....kDLLTk.....',
    '....kDDLLTTk....',
    '...kDDLLLTTtk...',
    '...kDLLLLTTtk...',
    '...kLLLLTTttk...',
    '...kLLLTTtttk...',
    '....kLLTTttk....',
    '.....kLTttk.....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  // GFX4 (§3.5b): gebackene '0'-Kontaktschatten bei vase/urn/chest ENTFERNT —
  // der Engine-Pass (§2.4 drawSoftShadow fuer echte Props) uebernimmt sie.
  // Scherben-Animation (generisch für Vase und Urne)
  prop_break_0: [
    '................',
    '................',
    '................',
    '....kb...Bk.....',
    '...kBk..kbk.....',
    '................',
    '..kQk.....kTk...',
    '.....kBbk.......',
    '....kbBBbk......',
    '.....kBbk.......',
    '..kTk.....kQk...',
    '................',
    '...kbk...kBk....',
    '....kB...bk.....',
    '................',
    '................',
  ],
  prop_break_1: [
    '................',
    '..b..........B..',
    '................',
    '.....k....k.....',
    '.B............b.',
    '................',
    '................',
    '.......bB.......',
    '................',
    '................',
    '.b............B.',
    '.....k....k.....',
    '................',
    '..B..........b..',
    '................',
    '................',
  ],
  // Schatztruhe: Holz mit Beschlägen, Gold-Schimmer im Spalt
  chest_closed: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kQJQQQQQQQJQQk.',
    '.kQYQQQQQQQQYQk.',
    '.kQYQQQkkQQQYQk.',
    '.kkkkkyy1ykkkkk.',
    '.kqYqqqkkqqqYqk.',
    '.kqYqjqqqqjqYqk.',
    '.kqqqqqqqqqqqqk.',
    '.kqYqjqqqqjqYqk.',
    '.kqqqqqqqqqqqqk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  chest_open: [
    '..kkkkkkkkkkkk..',
    '.kqqqqqqqqqqqqk.',
    '.kqQQJQQQQJQQqk.',
    '.kkkkkkkkkkkkkk.',
    '.kyyy1yyyy1yyyk.',
    '.kyYyyyYyyyYyyk.',
    '.kqYqqqqqqqqYqk.',
    '.kqYqjqqqqjqYqk.',
    '.kqqqqqqqqqqqqk.',
    '.kqYqjqqqqjqYqk.',
    '.kqqqqqqqqqqqqk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
    '................',
  ],
  // Heiltrank 10x10: leuchtend rote Flasche mit Korken
  potion: [
    '....kk....',
    '...kQQk...',
    '....kk....',
    '...k1xk...',
    '..kyxxxk..',
    '.koxxxxRk.',
    '.kxxxxRRk.',
    '.kxxRRRrk.',
    '..kkkkkk..',
    '..........',
  ],
  // Nebelschwade 32x16: EIN Grauton, weich auslaufende Ellipse
  fog_blob: [
    '................................',
    '............ffffff..............',
    '........ffffffffffff............',
    '.....ffffffffffffffffff.........',
    '...ffffffffffffffffffffffff.....',
    '..ffffffffffffffffffffffffffff..',
    '.ffffffffffffffffffffffffffffff.',
    '.ffffffffffffffffffffffffffffff.',
    '..ffffffffffffffffffffffffffff..',
    '...ffffffffffffffffffffffff.....',
    '.....ffffffffffffffff...........',
    '........ffffffff.......ffff.....',
    '..........ffff.........ff.......',
    '................................',
    '................................',
    '................................',
  ],
  // HUD-Herzen 8x8
  // GFX4 (§3.5c): 1px Innen-Highlight. heart_full = heller Rot-Glanz 'x' oben-
  // links (+ Bestands-'b'-Schimmer), heart_empty = kuehler Grau-Glanz 'S'.
  heart_full: [
    '.kk..kk.',
    'kxxkkRRk',
    'kxRRRRrk',
    'kRRRRrrk',
    '.kRRrrk.',
    '..kRrk..',
    '...kk...',
    '........',
  ],
  heart_empty: [
    '.kk..kk.',
    'kggkkggk',
    'kgSnnngk',
    'kgnnnngk',
    '.kgnngk.',
    '..kgnk..',
    '...kk...',
    '........',
  ],
  // Grufthund 16x12: hagerer Grabhund, Erd-Rampe z->p->v->P, V-Ridge auf dem
  // Ruecken, glutrotes Auge R. Blick nach rechts, main.js spiegelt.
  // GFX4-R2 (Jury M): Rueckenkamm 1 Stufe heller (durchgehende V-Ridge von
  // Schwanzansatz bis Schnauze, vorher von P/v unterbrochen) + heller Schwanzspitz.
  hound_0: [
    '..k.......kkk...',
    '.kVk....kkVppk..',
    '.kVk.kkkVVPvvpk.',
    'kVVVkVVVVVVVrRk.',
    '.kpvPvpvpvvvppk.',
    '.kppzpzppvvpkk..',
    '..kpvppvvppvk...',
    '..kppk...kppk...',
    '..kppk...kppk...',
    '..kzzk...kzzk...',
    '..kkkk...kkkk...',
    '................',
  ],
  hound_1: [
    '..k.......kkk...',
    '.kVk....kkVppk..',
    '.kVk.kkkVVPvvpk.',
    'kVVVkVVVVVVVrRk.',
    '.kpvPvpvpvvvppk.',
    '.kppzpzppvvpkk..',
    '..kpvppvvppvk...',
    '.kppk.....kppk..',
    '.kppk.....kppk..',
    '.kzk.......kzk..',
    '.kkk.......kkk..',
    '................',
  ],
  // Telegraph: geduckt, 2 px flacher und laenger, Laeufe gespannt
  hound_telegraph: [
    '................',
    '................',
    '................',
    '..........kkkk..',
    'kkkkkkkkkkVvvvk.',
    'kvVPVVVvvvrRvpk.',
    '.kvPzpzpvvvvvvvk',
    '.kppzpzppvvkbkbk',
    '..kpppppppvvkkk.',
    '..kpvvkkkvvpk...',
    '.kzpzk..kzpzk...',
    '.kkkk...kkkk....',
  ],
  // Leap: gestreckt in der Luft, Laeufe vor und zurueck
  hound_leap: [
    '..........kkk...',
    '.kk......kvvpk..',
    'kvkkkkkkkVvrRvk.',
    'kvVVVVVvvvvvvvvk',
    '.kpzpzpzpvvvkbbk',
    'kkppppppppvkkkk.',
    'kpvkkkkkkpvvk...',
    'kpk....kpvkpvk..',
    '.......kpk.kpk..',
    '........kk..kk..',
    '................',
    '................',
  ],
  // Down: liegt flach auf dem Bauch, Laeufe gespreizt, verwundbar
  hound_down: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..........kkk...',
    '.kkkkkkkkkvpvk..',
    'kvVVVVVvvvrRvpk.',
    'kpzpzpzpvvvvvvvk',
    'kpkpvkkkpvkpkbbk',
    '.kkkkk.kkkkk.kk.',
  ],
  // Tot: auf dem Ruecken, Laeufe nach oben, Auge zu
  hound_die: [
    '................',
    '................',
    '................',
    '................',
    '..k.k...k.k.....',
    '.kpkpk.kpkpk....',
    '.kvvpvkpvvk.....',
    'kvvvvvvvvvvkkk..',
    'kpzpzpzpvvvvvpk.',
    'kppppppppvvkkkk.',
    '.kkkkkkkkkkk....',
    '................',
  ],
  // Rostpanzer-Skelett 16x18: massig, Rost-Rampe 4->5->6, helle Rippen
  // auf dem Ruecken als Schwachstellen-Signal
  rust_0: [
    '.....k655k......',
    '....k65554k.....',
    '....k54445k.....',
    '...kNbbbbbbk....',
    '...kBkkbkkBk....',
    '....kbbkkbbk....',
    '..kk65bBbb56kk..',
    '.k655kkkkkk556k.',
    'k6554kbNNbk4556k',
    'k5544knb4nk4455k',
    'k554kkbNNbkk455k',
    '.kk4.knb4nk.4kk.',
    '.....kObbbOk....',
    '....kbOkkObk....',
    '....kbbk.kbbk...',
    '....kBbk.kBbk...',
    '....kOBk.kOBk...',
    '....kkkk.kkkk...',
  ],
  rust_1: [
    '.....k655k......',
    '....k65554k.....',
    '....k54445k.....',
    '...kNbbbbbbk....',
    '...kBkkbkkBk....',
    '....kbbkkbbk....',
    '..kk65bBbb56kk..',
    '.k655kkkkkk556k.',
    'k6554kbNNbk4556k',
    'k5544knb4nk4455k',
    'k554kkbNNbkk455k',
    '.kk4.knb4nk.4kk.',
    '.....kObbbOk....',
    '....kbOkkObk....',
    '...kbbk...kbbk..',
    '...kBbk...kBbk..',
    '...kOBk...kOBk..',
    '...kkkk...kkkk..',
  ],
  // Rostpanzer tot: Panzerplatte im Knochenhaufen
  rust_die: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '......k55k......',
    '.....k5554k.....',
    '.kbbkk5544kkbk..',
    'kbkNbk4544kbNbk.',
    'kBbbkkkkkkbbBbk.',
    '.kkkkkkkkkkkkk..',
  ],
  // Schild-Overlays: eigene Rostflaeche vor dem Koerper, Nieten Y
  shield_side: [
    '.kkkk.',
    'k6655k',
    'k6555k',
    'k6y54k',
    'k6554k',
    'k6554k',
    'k6y54k',
    'k6554k',
    'k5544k',
    'k5444k',
    '.k44k.',
    '..kk..',
  ],
  shield_up: [
    '..kkkkkkkk..',
    '.k66666555k.',
    'k6655555554k',
    'k6554444444k',
    '.kk4444444k.',
    '...kkkkkkk..',
  ],
  shield_down: [
    '.kkkkkkkkkk.',
    'k6666555554k',
    'k66y5555y54k',
    'k6555544444k',
    '.k55444444k.',
    '..kkkkkkkk..',
  ],
  // Funkenstern 8x8 beim Block
  block_spark: [
    '...y....',
    '.o.1.o..',
    '..y1y...',
    'y11111y.',
    '..y1y...',
    '.o.1.o..',
    '...y....',
    '........',
  ],
  // Knochen-Bumerang 10x10, 2 Rotationsphasen (um 90 Grad gedreht)
  boomerang_0: [
    '..kkkkkk..',
    '.kNNbbbbk.',
    '.kbbBBbbk.',
    '..kkkkbBk.',
    '.....kbBk.',
    '.....kbBk.',
    '.....kbOk.',
    '.....kbOk.',
    '.....kkOk.',
    '......kk..',
  ],
  boomerang_1: [
    '......kk..',
    '.....kkOk.',
    '.....kbOk.',
    '.....kbOk.',
    '.....kbBk.',
    '.....kbBk.',
    '..kkkkbBk.',
    '.kbbBBbbk.',
    '.kNNbbbbk.',
    '..kkkkkk..',
  ],
  // Boden-Drops 10x10: Schwert, Harnisch, Ring
  item_weapon: [
    '.......kk.',
    '......kIik',
    '.....kIik.',
    '.kk.kIik..',
    'kyykiik...',
    '.kyyik....',
    '..kyyk....',
    '.kjkyk....',
    'kqjkk.....',
    '.kk.......',
  ],
  item_armor: [
    '.kkkkkkkk.',
    'kJJknnkQjk',
    'kJQQQQQQjk',
    'kJQQQQQQjk',
    '.kQbQQbjk.',
    '.kQbQQbjk.',
    '..kQQQjk..',
    '..kQQQjk..',
    '...kkkk...',
    '..........',
  ],
  item_ring: [
    '....kk....',
    '...kIik...',
    '..kkiCkk..',
    '.kykkkkYk.',
    '.kyk..kYk.',
    '.kyk..kYk.',
    '..kykkYk..',
    '...kyYk...',
    '....kk....',
    '..........',
  ],
  // Glitzer-Overlay 8x8 fuer seltene Drops
  sparkle_0: [
    '........',
    '...I....',
    '...N....',
    '.INNNI..',
    '...N....',
    '...I....',
    '........',
    '........',
  ],
  sparkle_1: [
    '...I....',
    '...I....',
    '.I.N.I..',
    'IINNNII.',
    '.I.N.I..',
    '...I....',
    '...I....',
    '........',
  ],
  // Inventar-Icons 12x12 (auch abgedunkelt als Geister-Slots nutzbar)
  icon_weapon: [
    '.....kk.....',
    '....kIik....',
    '....kIik....',
    '....kIik....',
    '....kIik....',
    '....kiCk....',
    '..kkkiCkkk..',
    '.kyyYkkYyyk.',
    '....kjqk....',
    '....kjqk....',
    '....kyYk....',
    '.....kk.....',
  ],
  icon_armor: [
    '.kkk....kkk.',
    'kJJJkkkkQQjk',
    'kJJQQQQQQQjk',
    'kJQQQQQQQQjk',
    '.kQQQQQQQjk.',
    '.kQbQQQQbjk.',
    '.kQbQQQQbjk.',
    '..kQQQQQjk..',
    '..kQQQQQjk..',
    '..kkkkkkkk..',
    '............',
    '............',
  ],
  icon_ring: [
    '.....kk.....',
    '....kIik....',
    '...kkiCkk...',
    '..kyykkyYk..',
    '.kyk....kYk.',
    '.kyk....kYk.',
    '.kyk....kYk.',
    '..kyk..kYk..',
    '...kyyYYk...',
    '....kkkk....',
    '............',
    '............',
  ],
  // HUD-Icon 16x16: Knochen-Bumerang gross
  icon_boomerang: [
    '....kkkkkkkk....',
    '...kNNbbbbbbk...',
    '..kNbbbbBBbbbk..',
    '..kbbkkkkkbBbk..',
    '..kkk....kbBbk..',
    '..........kbBk..',
    '..........kbBk..',
    '..........kbBk..',
    '..........kbOk..',
    '..........kbOk..',
    '..........kbOk..',
    '..........kkOk..',
    '...........kOk..',
    '...........kkk..',
    '................',
    '................',
  ],
  // GRABWAECHTER (Boss) 24x32: Skelett-Koloss im Grabschleier, korrodierte
  // Pauldrons (Rost 4/5/6), gruene Seelenglut (7/8) in den Augen, Zweihaender
  // (Klinge C/i/I, Griff Y/y). Silhouetten je Zustand klar unterscheidbar
  // (3-Kanal-Telegraphie: Form + Helligkeit + Bewegungsstopp). Blick nach unten,
  // main.js spiegelt fuer den Sturm (Flip-Key am Listenende).
  // idle: aufrecht, Zweihaender vor dem Koerper in den Boden gestuetzt.
  warden_idle: [
    '.......k........k.......',
    '......k8k......k8k......',
    '.....k86k.7887.k68k.....',
    '....kk6b7bbNNbb7b6kk....',
    '...k647bbbbbbbbbbb744k..',
    '..k6BBbbbbbbbbbbbbBB4k..',
    '..k6Bb7788bbbb8877bB4k..',
    '..k6Bb7888bbbb8887bB4k..',
    '..k5Bbb77bbbbbb77bbB4k..',
    '...kBbbbbOObbOObbbBBk...',
    '...kkBbbbObbbbObbBBkk...',
    '..k64kBbbkOnnOkbBk44k...',
    '.k6554kkkkkkkkkkk5544k..',
    'k65554kBbbYYYYbbBk55444k',
    'k6554UukbbYyyYbbkuU5544k',
    '.kUUuuBbbkiCCikbbBuuUk..',
    '..kuuUBBbbkiikbbBBUuuk..',
    '..kuXUUBObbiCibbOBUUXuk.',
    '..kuXXUUBbbiCibbBUUXXuk.',
    '...kuXXUBObiCibOBUXXuk..',
    '...kuuXXBbbiCibbBXXuuk..',
    '....kuuXBObiIibOBXuuk...',
    '....kOBbBBbiCibBBbBOk...',
    '...kOBObkbbiCibbkOBOk...',
    '...kBbOk.kbiCibk.kObBk..',
    '..kBbbk..kbiIibk..kbbBk.',
    '..kOBk...kbiCibk...kBOk.',
    '..kBbk...kbiCibk...kbBk.',
    '..kkk....kkiIikk....kkk.',
    '.........kbiCibk........',
    '.........kkiCikk........',
    '..........kkkkk.........',
  ],
  // walk_0/1: langsamer Stalk-Gang, Klinge geschultert, Beine wechseln
  warden_walk_0: [
    '.......k........k.......',
    '......k8k......k8k......',
    '.....k86k.7887.k68k.....',
    '....kk6b7bbNNbb7b6kk....',
    '...k647bbbbbbbbbbb744k..',
    '..k6BBbbbbbbbbbbbbBB4k..',
    '..k6Bb7788bbbb8877bB4k..',
    '..k6Bb7888bbbb8887bB4k..',
    '..k5Bbb77bbbbbb77bbB4k..',
    '...kBbbbbOObbOObbbBBk...',
    '...kkBbbbObbbbObbBBkk...',
    '..k64kBbbkOnnOkbBk44k...',
    '.k6554kkkkkkkkkkk5544k..',
    'k65554kBbbbbbbbBk655444.',
    'k6554UukbbbbbbbkuU65544.',
    '.kUuuBBbbbbbbbbBBuuUk...',
    '..kuuUUBBbbbbbbBBUUuuk..',
    '..kuXUUUBObbbbOBUUUXuk..',
    '..kuXXUUBBbbbbBBUUXXuk..',
    '...kuXXUBObbbbOBUXXuk...',
    '...kuuXXBBbbbbBBXXuuk...',
    '....kuuXXBObbOBXXuuk....',
    '.....kOBBbBBBBbBBOk.....',
    '....kBbOk...kOBk........',
    '...kOBbk....kBbk........',
    '...kBbk.....kkk.........',
    '..kOBk..................',
    '..kBbk..................',
    '..kkk...................',
    '........................',
    '........................',
    '........................',
  ],
  warden_walk_1: [
    '.......k........k.......',
    '......k8k......k8k......',
    '.....k86k.7887.k68k.....',
    '....kk6b7bbNNbb7b6kk....',
    '...k647bbbbbbbbbbb744k..',
    '..k6BBbbbbbbbbbbbbBB4k..',
    '..k6Bb7788bbbb8877bB4k..',
    '..k6Bb7888bbbb8887bB4k..',
    '..k5Bbb77bbbbbb77bbB4k..',
    '...kBbbbbOObbOObbbBBk...',
    '...kkBbbbObbbbObbBBkk...',
    '..k64kBbbkOnnOkbBk44k...',
    '.k6554kkkkkkkkkkk5544k..',
    'k65554kBbbbbbbbBk655444.',
    'k6554UukbbbbbbbkuU65544.',
    '.kUuuBBbbbbbbbbBBuuUk...',
    '..kuuUUBBbbbbbbBBUUuuk..',
    '..kuXUUUBObbbbOBUUUXuk..',
    '..kuXXUUBBbbbbBBUUXXuk..',
    '...kuXXUBObbbbOBUXXuk...',
    '...kuuXXBBbbbbBBXXuuk...',
    '....kuuXXBObbOBXXuuk....',
    '.....kOBBbBBBBbBBOk.....',
    '........kOBk...kBbOk....',
    '........kBbk...kOBbk....',
    '........kkk....kBbk.....',
    '...............kOBk.....',
    '...............kBbk.....',
    '...............kkk......',
    '........................',
    '........................',
    '........................',
  ],
  // windup_a (Muster A Rundumschlag): Klinge HOCH ueber dem Kopf, Arme oben
  warden_windup_a: [
    '...........kiIik........',
    '..........kbiCibk.......',
    '.......k...kiCik...k....',
    '......k8k..kiCik..k8k...',
    '.....k86kk.kiIik.kk68k..',
    '....kk6bBbkkiCikkbBb6kk.',
    '...k44BbbbbkiCikbbbbB44k',
    '..k4BBbbbbbkiIikbbbbBB4k',
    '..k4Bb7788bbkCikb8877B4k',
    '..k4Bb7888bbbbbbb8887B4k',
    '..k4Bbb77bbbbbbbb77bbB4k',
    '...kBbbbbOObbbbOObbbbBk.',
    '...kkBbbbObbbbbbObbbBkk.',
    '..k44kBbbkkbbbbkkbBk44k.',
    '.k4556kkkYYYYYYkkk6554k.',
    'k45556kBbbYyyyyYbbBk6554',
    'k4556UukBBbbbbbbBBkuU654',
    '.kUUuuBBBbbbbbbbBBBuuUk.',
    '..kuuUUBObbbbbbOBUUuuk..',
    '..kuXUUUBBbbbbBBUUUXuk..',
    '..kuXXUUBObbbbOBUUXXuk..',
    '...kuXXUBBbbbbBBUXXuk...',
    '...kuuXXBObbbbOBXXuuk...',
    '....kOBBBbbbbbbBBBOk....',
    '...kOBObk.kkkk.kOBOk....',
    '...kBbOk..kBbBk..kObk...',
    '..kBbbk...kOBk...kbbBk..',
    '..kOBk....kBbk....kBOk..',
    '..kBbk....kkk.....kbBk..',
    '..kkk............kkkk...',
    '........................',
    '........................',
  ],
  // windup_b (Muster B Sturm): geduckte Anlauf-Pose, Klinge weit zurueckgezogen
  warden_windup_b: [
    '....k........k..........',
    '...k8k......k8k.........',
    '..k86k.kkkk.k68k........',
    '.kk6bkkbNNbkkb6kk.......',
    'k44BbbbbbbbbbbbB44k.....',
    '4BBbbbbbbbbbbbbBB4k.....',
    '4Bb7788bbbb8877bB4k.....',
    '4Bb7888bbbb8887bB4k.....',
    '4Bbb77bbbbbb77bbB4k.....',
    'kBbbbbOObbOObbbbBk......',
    'kkBbbbObbbbObbbBkk......',
    'k44kBbbkbbbbkbBk44k.....',
    '4556kkkkkkkkkkk6554kkk..',
    '4556kBbbbbbbbBk6554YYYk.',
    '456UukbbbbbbbkuU6yYyyYk.',
    'kUuuBBbbbbbbbbBBiCCCCbk.',
    'kuUUBBbbbbbbbbBBiiiiik..',
    'kuXUUBObbbbbbOBUCiik....',
    'kuXXUUBBbbbbBBUUUk......',
    'kuuXXBObbbbOBUXXuk......',
    '.kuXXBBbbbbBBXXuk.......',
    '.kOBBBbbbbbbBBBOk.......',
    'kOBObkkkkkkkkkOBOk......',
    'kBbOk..kbbk...kOBObk....',
    'kOBk...kBbBk...kBbbBk...',
    'kBbk...kOBk.....kOBk....',
    'kkk....kBbk.....kBbk....',
    '.......kkk......kkk.....',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // dash: Sturm nach rechts, Koerper gestreckt, Klinge vorgestossen
  warden_dash: [
    '.k........k.............',
    'k8k......k8k............',
    '86k.kkkk.k68k...........',
    '6bkkbNNbkkb6kk..........',
    '4BbbbbbbbbbbbB44k.......',
    'BbbbbbbbbbbbbbBB4k......',
    'b7788bbbb8877bB4k......C',
    'b7888bbbb8887bB4k....CiI',
    'bb77bbbbbb77bbB4k..CiiCi',
    'BbbbOObbOObbbbBkiiiiiiC.',
    'kBbbbObbbbObbbBYyyyyk...',
    '4kBbbkbbbbkbBkYYYYkk....',
    '56kkkkkkkkkkk6554k......',
    '56kBbbbbbbbBk65554k.....',
    '6UukbbbbbbbkuU6554k.....',
    'UuuBBbbbbbbbbBBuuU6k....',
    'uUUBBbbbbbbBBUUuuk......',
    'XUUUBObbbbOBUUUXuk......',
    'XXUUBBbbbbBBUUXXuk......',
    'uXXUBObbbbOBUXXuk.......',
    'uuXXBBbbbbBBXXuuk.......',
    'kOBBBbbbbbbBBBOk........',
    'kOBObk..kkk..kbOk.......',
    'kBbbk..kOBObk.kbBk......',
    'kOBk...kBbbBk..kkk......',
    'kBbk....kOBk............',
    'kkk.....kBbk............',
    '........kkk.............',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // stuck: Klinge TIEF im Boden vorne, Boss vornuebergebeugt (Strafenfenster)
  warden_stuck: [
    '........................',
    '........................',
    '.......k........k.......',
    '......k8k......k8k......',
    '.....k86k.7887.k68k.....',
    '....kk6b7bbNNbb7b6kk....',
    '...k447bbbbbbbbbbb744k..',
    '..k4BBbb77bbbb77bbBB4k..',
    '..k4Bbb788bbbb887bbB4k..',
    '..k4Bbbb77bbbb77bbbB4k..',
    '..k4BbbbbOObbOObbbbB4k..',
    '...kBbbbbObbbbObbbbBk...',
    '..k44kBbkkbbbbkkbBk44k..',
    '.k4556kkkkkkkkkkk6554k..',
    'k45556BbbbbbbbbbBk6554k.',
    'k4556UuBBbbbbbbBBuU654k.',
    '.kUUuuUBObbbbbbOBUuuUk..',
    '..kuuUUBBbbbbbbBBUUuuk..',
    '..kuXUUBObbbYYbbOBUXuk..',
    '..kuXXUBBbbYyyYbbBUXuk..',
    '...kuXXBObbkiCikbbOXuk..',
    '...kuuXBBbbbiCibbbBXuk..',
    '....kOBBbbbbiIibbbBOk...',
    '....kkOBObbbiCibbOBk....',
    '.....kBbObk.iCi.kbBk....',
    '.....kOBk...iIi...kk....',
    '.....kBbk...iCi.........',
    '.....kkk...kiCik........',
    '..........kkiIikk.......',
    '..........kbiCibk.......',
    '..........kkiiikk.......',
    '...........kkkkk........',
  ],
  // summon (Ruf-Pose): beide Arme weit erhoben, Klinge in der Rechten hoch
  warden_summon: [
    '.k...............kiIik..',
    'k8k.............kbiCibk.',
    '86k.kkkk.k.......kiCik..',
    '6bkkbNNbkk8k.....kiCik..',
    '4BbbbbbbbbBb.....kiIik..',
    'BBbbbbbbbbbBk....kiCik..',
    'Bb7788bbbb887k...kiCik..',
    'Bb7888bbbb8887b..kiIik..',
    'Bbb77bbbbbb77bB.bbkCikbb',
    'BbbbOObbOObbbbBbbbbbbbbb',
    'kBbbbObbbbObbbBkkkYYYYYk',
    'kkBbbkbbbbkbBkkbbYyyyyYk',
    'YYYkkkkkkkkkkYYYbbbbbbbk',
    'yYYYbbbbbbbbYYYyBBbbbbBk',
    'kYYUukbbbbbkuUYYkBObbOBk',
    '.kUUuBBbbbbbbBBuUUkBBBk.',
    '..kuuUBBbbbbBBUuuk.kkk..',
    '..kuXUUBObbbbOBUUXuk....',
    '..kuXXUBBbbbbBBUXXuk....',
    '...kuXXBObbbbOBXXuk.....',
    '...kuuXBBbbbbBBXuuk.....',
    '....kOBBbbbbbbBBOk......',
    '...kOBObk.kk.kbOBOk.....',
    '...kBbOk..kk...kObBk....',
    '..kBbbk..kOBObk.kbbBk...',
    '..kOBk...kBbbBk..kBOk...',
    '..kBbk....kOBk...kbBk...',
    '..kkk.....kBbk...kkk....',
    '..........kkk...........',
    '........................',
    '........................',
    '........................',
  ],
  // die: bricht in einen Knochenhaufen, Seelenglut erlischt (7 statt 8)
  warden_die: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '.............k..........',
    '...kk......kkbkk........',
    '..kbBk...kkbOBObk.......',
    '.kBObbkkkkBbbbbbBk......',
    'kOb7bBBbb77bbbb7bBk.....',
    'kbb7bbbbb77bbbb77bbk....',
    'kOBbbOObbbbbbObbbbBOk...',
    '.kBObkYYkbbkYYkbbkOBk...',
    'kOBbkYyyYbkYyyYbbbkbBk..',
    'kBbbBiCCikkiCCibbBObbBk.',
    'kOBbbbiikkkkiikbbBbbbOk.',
    'kkOBBbbbBbbbBbbBBbbBBkk.',
    '.kkOBObbObbObbObbObkk...',
    '..kkbBbbkbbkbbkbBbkk....',
    '...kkOBbbbbbbbbBOkk.....',
    '....kkbBObbbbOBbkk......',
    '.....kkbbBbbBbbkk.......',
    '......kkOBbbBOkk........',
    '.......kkkkkkkk.........',
    '........................',
    '........................',
  ],
  // elite_glow 8x8 (§2.4): Glut-Augen R, Kante o. Overlay ueber Elite-Koepfen
  elite_glow: [
    '..o..o..',
    '.oRooRo.',
    'ooRRRRoo',
    '.oRooRo.',
    '..oooo..',
    '...oo...',
    '........',
    '........',
  ],
  // levelup_0/1 16x16: aufsteigender Level-Up-Ring, Gold (o/y/1) + Knochenweiss N
  levelup_0: [
    '................',
    '................',
    '................',
    '.....oyyyyo.....',
    '...oyy1NN1yyo...',
    '..oy1o....o1yo..',
    '.oy1o......o1yo.',
    '.oyo........oyo.',
    '.oyo........oyo.',
    '.oy1o......o1yo.',
    '..oy1o....o1yo..',
    '...oyy1NN1yyo...',
    '.....oyyyyo.....',
    '................',
    '................',
    '................',
  ],
  levelup_1: [
    '......NN........',
    '....oy..yo......',
    '..oy1o..o1yo....',
    '.oyo......oyo.N.',
    '.yo........oy...',
    'N1..........1N..',
    'yo..........oy..',
    'yo..........oy..',
    '.yo........oyN..',
    '.oyo......oyo...',
    '..1yo....oy1....',
    '...oy1..1yo.....',
    'N....oyyyo......',
    '.......NN.......',
    '................',
    '................',
  ],
  // icon_key 8x8: Boss-Schluessel (Gold), erscheint im HUD ab Fund
  icon_key: [
    '.kkk....',
    'kyYYk...',
    'ky1yk...',
    'kyYyk...',
    '.kyk....',
    '.kyk.kk.',
    '.kyykyk.',
    '..kkkkk.',
  ],

  // ==========================================================================
  // SLICE 6 — DIE FUENF NPCs VON GRAMFELD (16x24 = Spielermass) + Blase.
  // APPEND-ONLY ANS LISTENENDE: main.js:88 baut die Canvases in dieser
  // Objekt-Reihenfolge; check_main_slice1 und check_inventory_slice2 mappen
  // Canvas -> Sprite ueber die Erzeugungsfolge. Ein Einschub weiter oben
  // faerbt beide Alt-Tests rot.
  // ZWEI FRAMES je NPC (Muster enemies.js:628: `${kind}_0`/`_1` im 2er-
  // Umlauf fuer Stehen UND Gehen). Frame 1 senkt den Rumpf um 1 px und
  // stellt die Beine in Schritt — getrennte Walk-Grids verlangt der
  // Bestand nicht. DAZU je ein `_talk`-Sprech-Frame ganz am Listenende
  // (SPEC Rev 1 §2.1/§2.2; npcs.js:185 fragt ihn im Dialog ab).
  // SCHLUESSEL-REGEL: der Teil zwischen 'npc_' und dem Suffix ist WOERTLICH
  // die npcSpawn-id aus map_dorf.js — npcs.js baut den Schluessel daraus.
  // KLEIDERREGEL: nie u/U/X/Z (Helden-Violett) als Flaeche. Verwendet sind
  // Leder q/j/Q/c/J, Rost 4/5/6, Leinen O/B/b/N, Stein g/s/S, Haut h/2 und
  // 'G' = Krapp-Altrosa (Leitfarbe Hedda, Akzent Corm).
  // ==========================================================================
  // BRAN DER SCHMIED — Lederschurz J/c mit Rostnieten, blosse Arme, grauer Bart.
  npc_bran_0: [
    '.......__hk.....',
    'sSFs._hhhhhk....',
    'sSFF_hhhhhhh2k..',
    'sSsk_hnnnnn22k..',
    'kssk2h22222h2k..',
    '...j2hkhhk2h2k..',
    '...j2hh22hhh2k..',
    '...jObbbBBBOOk..',
    '...jObbBBBBOOk..',
    '._;jOBBBBBOO;k..',
    '._;jOOBBBBB;;;k.',
    '.2hj;QBBB;Q;hh2k',
    '.2hj;Q;B;;Q;hh2k',
    '.2hh;Q;;;;Q;hh2k',
    '.._QQQSQQQQQhh2k',
    '.._;;?;;;:::hh2k',
    '.._;;?;;::::hh2k',
    '..?;;;;;;::::hhk',
    '..??;?;::::::k..',
    '..??;?;;:::::k..',
    '..?;?;;;:::::k..',
    '..?;?;;;:::::k..',
    '..jjjjk.jjjjk...',
    '..jqqqk.jqqqk...',
  ],
  npc_bran_1: [
    '.......__hk.....',
    '.SFs._hhhhhk....',
    'sSFF_hhhhhhh2k..',
    'sSsk_hnnnnn22k..',
    'kssskhh2222h2k..',
    '...j2hkhhk2h2k..',
    '...j2hh22hh22k..',
    '...jObbBBBBBOOk.',
    '._;jObbBBBBOOk..',
    '._;j:OBBBBOO;;k.',
    '.2hj:OBBBOOO;;k.',
    '.2hj;QBBBOQ;hh2k',
    '.2hh;Q;BB;Q;hh2k',
    '..2h;Q;;;;Q;hh2k',
    '._QQQSQQQQQQhh2k',
    '.;;;;;;;;;::hh2k',
    '._;;;;;;::::hh2k',
    '.?;;;;;;:::::hhk',
    '.?;;;;;;:::::k..',
    '.?;;;;;;;::::k..',
    '.?;?;;;;:::::k..',
    '.?;?;;;;:::::k..',
    '.jjjjk...jjjjk..',
    '.jqqqk...jqqqk..',
  ],
  // ALTE HEDDA — Krapp-Umhang 'G' (LEITFARBE der Umwidmung), r-Falten, Stock.
  npc_hedda_0: [
    '.....__k........',
    '...._bbbBk......',
    '..._bbbbBBk.....',
    '...ObnnnnnBk....',
    '...Ob22222Bk....',
    '...Obhkhk2Bk....',
    '...Ob2h222Bk....',
    '...OB2hh22BBk...',
    '.._BB22222OOOk..',
    '._BBBBBBBOOOO!k.',
    '._BBBBBBOOOO!!k.',
    '._BBBBBBOOOO!!k.',
    '.hhh%BBOOhJG!k..',
    '..%%%%%GGGJG!k..',
    '..%%%%%%GJ!!k...',
    '..%%%%%GQG!k....',
    '..%%%%%GQG!k....',
    '...%%%%GQG!k....',
    '...%%%%Q%%!k....',
    '...%%%%Q%%!k....',
    '....%%j%%!k.....',
    '....%j%%G!k.....',
    '....j%%%G!k.....',
    '...jjjk.jjk.....',
  ],
  npc_hedda_1: [
    '.....__k........',
    '...._bbbBk......',
    '..._bbbbBBk.....',
    '...ObnnnnnBk....',
    '...Ob22222Bk....',
    '...Obhkhk2Bk....',
    '...Ob2h222BBk...',
    '.._BB2hh22BOOk..',
    '._BBB22222OOOOk.',
    '_BBBBBBBBOOOOOOk',
    '._BBBBBBOOOOO!k.',
    '.!BBBBBBOOOO!!k.',
    '..hh%BBOOhJG!k..',
    '..%%%%%GGGJG!k..',
    '..%%%%%GQGGk....',
    '..%%%%%GQGGGk...',
    '..%%%%%GQG!k....',
    '...%%%GGQG!k....',
    '...%%%%Q%G!k....',
    '...%%%%Q%%!k....',
    '....%%jGG!k.....',
    '....%j%GG!k.....',
    '....j%%GG!kk....',
    '...jjjk.jjk.....',
  ],
  // VATER CORM — dunkle Kutte n/g/s, Krapp-Stola als einziger Akzent, Buch.
  npc_corm_0: [
    '.......|(.......',
    '......|((k......',
    '.....|((((k.....',
    '....|)(((((k....',
    '....|)((((((k...',
    '....&)nnnnn(k...',
    '....&)22h22(k...',
    '....&)hkhk2(k...',
    '....&)hh222(k...',
    '....&&bbBBB(k...',
    '...|)(bbbBB&k...',
    '...|)(GGGG&&&k..',
    '...|)(G&hQJJJJQk',
    '...&)(G&hQbbbbQk',
    '...&)(G&&QJJJJQk',
    '..&)(GG((&&&&k..',
    '..&)(GG((&&&&k..',
    '..&)(GG((&&&&k..',
    '..&)(G((((&&&k..',
    '..&)((((((&&&k..',
    '..&)((((((&&k...',
    '..&)(((((&&&&k..',
    '..&)(((((&&&&k..',
    '..&&(((nn&&&&k..',
  ],
  npc_corm_1: [
    '.......|(.......',
    '......|((k......',
    '.....|(((k......',
    '....|)(((((k....',
    '....|)((((((k...',
    '....&)nnnnn(k...',
    '....&)22h22(k...',
    '....&)hkhk2(k...',
    '....&)hh222((k..',
    '...(((bbBBB((k..',
    '...|)(bbbB(&&k..',
    '...|)(GGGG(&&k..',
    '...|)(G&hQJJJJQk',
    '...&)(G&hQbbbbQk',
    '...&)(G&&QJJJJQk',
    '..&))(GG((&&k...',
    '..&))(GG((&&k...',
    '..&))(G((((&k...',
    '..&))((((((&k...',
    '..&)((((((&&k...',
    '..&)((((((&&&k..',
    '..&)(((((&&&&k..',
    '..&)(((((&&&&k..',
    '..&&(((n&&&&&k..',
  ],
  // MILE, DAS BOTENKIND — kleiner Wuchs (Kopf ab Zeile 4), Leinenkittel, Tasche.
  npc_mile_0: [
    '................',
    '................',
    '................',
    '....jj__jjk.....',
    '....jjccjjk.....',
    '....jccccjjk....',
    '....jccjjcjk....',
    '....jhkhkh2k....',
    '....jhhhh22k....',
    '....2h22hh2k....',
    '....2hhhh2k.....',
    '.....hhhh2k.....',
    '.....]]][[k.....',
    '....]]]]JJ[k....',
    '....]]]JJ[[k....',
    '.qJJ]]JJ[[@k....',
    '.qJhhJJ[[[@hk...',
    '.qJQ[[[[[[@hk...',
    '.qJQ[[[[[[@k....',
    '.kk@[[[[[[@k....',
    '....@[[[[[@k....',
    '....2hk.2hk.....',
    '....2hk.2hhk....',
    '...Jqqk.Jqqk....',
  ],
  npc_mile_1: [
    '................',
    '................',
    '................',
    '.....jj__jjk....',
    '.....jjccjjk....',
    '.....jccccjjk...',
    '.....jccjjcjk...',
    '.....jhkhkh2k...',
    '.....jhhhh22k...',
    '.....2h22hh2k...',
    '.....2hhhh2k....',
    '......hhhh2k....',
    '.....]]][[k.....',
    '....]]]]JJ[k....',
    '....]]]JJ[[hk...',
    '.qJJ]]JJ[[@hk...',
    'qJJhhJJ[[[@2k...',
    'qJJQ[[[[[[@k....',
    'qJQQ[[[[[@k.....',
    'kkk@[[[[[[@k....',
    '....@[[[[[@k....',
    '....2hk.2hk.....',
    '.....2hk2hhk....',
    '.....JqkJqqk....',
  ],
  // DER TORWAECHTER — Eisenhaube g/s/S, Rostpanzer 4/5/6, Speer rechts.
  // SCHLUESSEL-PAARUNG (Fixer R1, V-SPEC BLOCKER): npcs.js:185-187 bildet den
  // Sprite-Schluessel als `npc_${n.id}_<frame>`, und die id des fuenften NPC
  // heisst in map_dorf.js/npc_dialoge.js/quest.js 'torwaechter'. Der frueher
  // hier stehende Kurzname 'npc_wache_*' lief in allen drei drawNpc-Fallbacks
  // ins Leere — der Torwaechter wurde NICHT gezeichnet.
  npc_torwaechter_0: [
    '...............I',
    '..............iI',
    '....||Iik.....ii',
    '...|iiiiCk....ci',
    '...CiiiiCCk...Jc',
    '...CnnnnCk....Jc',
    '...Chkhk2k....Jc',
    '...Chhh22k....Jc',
    '...Chnnh2k....Jc',
    '...C2hh2Ck....Jc',
    '||6666666554kJc.',
    '|66666665554kJc.',
    '.|556656654k.Jc.',
    '.|556656654k.Jc.',
    '.6556656542hhhc.',
    '.6554444454k.Jc.',
    '.6556656554k.Jc.',
    '..656656554kJc..',
    '..kqqjjqqjk.Jc..',
    '.||55665564kJc..',
    '..66544566k.Jc..',
    '..6654665k.Jc...',
    '..6654665k.Jc...',
    '.jjqqkjjqqkJc...',
  ],
  npc_torwaechter_1: [
    '...............I',
    '..............iI',
    '....||Iik.....ii',
    '...|iiiiCk....ci',
    '...CiiiiCCk...Jc',
    '...CnnnnCk....Jc',
    '...C2hkhkk....Jc',
    '...C2hhh2k....Jc',
    '...Chnnh2k....Jc',
    '...C2hh2Ck....Jc',
    '.|6666666554kJc.',
    '|66666665554kJc.',
    '.|556656654k.Jc.',
    '.|556656654k.Jc.',
    '.6556656542hhhc.',
    '.6554444454k.Jc.',
    '.6556656554k.Jc.',
    '..656656554kJc..',
    '.kqqjjqqjk..Jc..',
    '||55665564k.Jc..',
    '.66544566k..Jc..',
    '.6654665k...Jc..',
    '.6654665k...Jc..',
    'jjqqkjjqqk..J...',
  ],
  // Hinweisblase ueber Quest-Gebern (8x8).
  // SLICE 6 PHASE 4a: die Platte war mit N (L233) nach der Flamme das Hellste
  // im Bild. Jetzt warmes Pergament B (L139) mit Innenfeld O (L102); die
  // Glyphe bleibt r (L52), Kontrast 87 L.
  // SCHLUESSEL-PAARUNG (Fixer R1, V-SPEC MAJOR): npcs.js:218 liest gfx.npc_blase.
  // Unter dem frueheren Namen 'npc_bubble' war die '!'-Blase ein stiller No-op.
  npc_blase: [
    '.kkkkkk.',
    'kBBBBBBk',
    'kBOrrOBk',
    'kBOrrOBk',
    'kBOrrOBk',
    'kBBOOBBk',
    'kBOrrOBk',
    '.kkkkkk.',
  ],

  // ==========================================================================
  // SPRECH-FRAMES (Fixer R1, V-SPEC MAJOR "Sprech-Frames fehlen vollstaendig").
  // SPEC Rev 1 §2.1/§2.2 nennt neben dem 2-Frame-Idle ausdruecklich einen
  // Sprech-Frame; npcs.js:185 fragt ihn als `npc_<id>_talk` ab und fiel bisher
  // still auf den Idle-Frame zurueck.
  // BAUART: Grundlage ist IMMER Frame _0 (gleiche Fusslinie, gleicher Rumpf —
  // im Dialog steht der NPC still), veraendert ist AUSSCHLIESSLICH die
  // Mundzeile: aus der geschlossenen Lippe '22' wird die offene Mundhoehle
  // '2kk2' (k = Umriss/Schatten, 2 = dunkler Hautton als Lippenrand). Ein
  // groesserer Ausschlag flackert bei 8x8-Kopfgroesse.
  // APPEND-ONLY ANS LISTENENDE (§0.6): die Indizes 0..74 des Bestands und die
  // Reihenfolge der zehn Idle-Grids bleiben unberuehrt.
  // ==========================================================================
  npc_bran_talk: [
    '.......__hk.....',
    'sSFs._hhhhhk....',
    'sSFF._hhhhhhh2k.',
    'sSsk._hnnnnn2Bk.',
    'kssk.2h22222h2k.',
    '...j.2hkhhk2h2k.',
    '...j.2h2kkhhh2k.',
    '...jObb22BBBOOk.',
    '...jObbBBBBOOk..',
    '._;jOBBBBBOO;h2k',
    '._;jOOBBBOOO;h2k',
    '.2hj;QBBB;Q;hh2k',
    '.2hj;Q;B;;Q;;h2k',
    '.2hh;Q;;;;Q;;;2k',
    '.._QQQSQQQQQ;;;k',
    '.._;;?;;;:::;;;k',
    '.._;;?;;:::::::k',
    '..??;?;;;::::::k',
    '..??;?;::::::k..',
    '..??;?;;:::::k..',
    '..?;?;;;:::::k..',
    '..?;?;;;:::::k..',
    '..jjjjk.jjjjk...',
    '..jqqqk.jqqqk...',
  ],
  npc_hedda_talk: [
    '.....__k........',
    '...._bbbbk......',
    '...._bbbbBBk....',
    '....ObnnnnnBk...',
    '....Ob22222Bk...',
    '....Obhkhk2Bk...',
    '....Ob2kk22Bk...',
    '...BB22hh22BBk..',
    '.._BB22222OOOk..',
    'h_BBBBBBBOOOO!k.',
    'h2BBBBBBOOOO!!k.',
    '2hhBBBBBOOOO!!k.',
    '.hhh%BBOOhJG!k..',
    '..%%%%%GGGJG!k..',
    '..%%%%%%GJ!!k...',
    '..%%%%%GQG!k....',
    '..%%%%%GQG!k....',
    '...%%%%GQG!k....',
    '...%%%%Q%%!k....',
    '...%%%%Q%%!k....',
    '....%%j%%!k.....',
    '....%j%%G!k.....',
    '....j%%%G!k.....',
    '...jjjk.jjk.....',
  ],
  npc_corm_talk: [
    '.......|(.......',
    '......|((k......',
    '.....|((((k.....',
    '....|)(((((k....',
    '....|)((((((k...',
    '....&)nnnnn(k...',
    '....&)22h22(k...',
    '....&)hkhk2(k...',
    '....&)h2kk2(k...',
    '....&&bb222(k...',
    '...|)(bbb(&(hQJQ',
    '...|)(GGG(&hQbbQ',
    '...|)(G&&&&hQJJQ',
    '...&)(G&&&&&&k..',
    '...&)(G&&&&&k...',
    '..&)(GG((&&&&k..',
    '..&)(GG((&&&k...',
    '..&)(G((((&&&k..',
    '..&)((((((&&&k..',
    '..&)((((((&&&k..',
    '..&)(((((&&&&k..',
    '..&)(((((&&&&k..',
    '..&)(((((&&&&k..',
    '..&&(((nn&&&&k..',
  ],
  npc_mile_talk: [
    '................',
    '................',
    '....jj__jjk.....',
    '....jjccjjk.....',
    '....jccccjjk....',
    '....jccjjcjk....',
    '....jhkhkh2k....',
    '....jhh2h22k....',
    '....2hkkhh2k....',
    '....2hnnh22k....',
    '....2hhhhh2k....',
    '.....2hhh2k.....',
    '....]]]][[k.....',
    '...]]]]]JJ[hk...',
    '...]]]]JJ[[hk...',
    '.qJJ]]JJ[[@2k...',
    '.qJhhJJ[[[@k....',
    '.qJQ[[[[[[@k....',
    '.qJQ[[[[[[@k....',
    '.kk@[[[[[[@k....',
    '....@[[[[[@k....',
    '....2hk.2hk.....',
    '....2hk.2hhk....',
    '...Jqqk.Jqqk....',
  ],
  npc_torwaechter_talk: [
    '...............I',
    '..............iI',
    '....||Iik.....ii',
    '...|iiiiCk....ci',
    '...CiiiiCCk...Jc',
    '...CnnnnCk....Jc',
    '...Ckhkh2k....Jc',
    '.hhChhhh2k....Jc',
    '.2hCkkkh2k....Jc',
    '.2hChhhh2k....Jc',
    '||6666666554kJc.',
    '|66666665554kJc.',
    '.|556656654k.Jc.',
    '.|556656654k.Jc.',
    '.6556656542hhhc.',
    '.6554444454k.Jc.',
    '.6556656554k.Jc.',
    '..656656554k.Jc.',
    '..kqqjjqqjk..Jc.',
    '.||55665564k.Jc.',
    '..66544566k..Jc.',
    '..6654665k..Jc..',
    '..6654665k..Jc..',
    '.jjqqkjjqqk.J...',
  ],
};
